PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE `Excercise` (`name` TEXT NOT NULL, `muscleGroup` TEXT NOT NULL, `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL);
INSERT INTO Excercise VALUES('Bench Press','Chest',1);
INSERT INTO Excercise VALUES('Military Press','Shoulders',2);
INSERT INTO Excercise VALUES('Bicep Curl','Biceps',3);
INSERT INTO Excercise VALUES('Sit-Ups','Abs',4);
INSERT INTO Excercise VALUES('Tricep Pushdown','Triceps',5);
INSERT INTO Excercise VALUES('Lat Pulldown','Back',6);
INSERT INTO Excercise VALUES('Leg Press','Legs',7);
INSERT INTO Excercise VALUES('Shoulder Press','Shoulders',8);
INSERT INTO Excercise VALUES('Squat','Legs',9);
INSERT INTO Excercise VALUES('Seated Row','Back',10);
INSERT INTO Excercise VALUES('Plank','Abs',11);
INSERT INTO Excercise VALUES('Pec Fly','Chest',12);
INSERT INTO Excercise VALUES('Back Extention','Back',13);
COMMIT;