package com.example.fitnessapp

import android.os.Bundle
import android.text.Editable
import android.text.TextWatcher
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import androidx.recyclerview.widget.DividerItemDecoration
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.room.Room
import com.example.fitnessapp.database.Excercise
import com.example.fitnessapp.database.ExcerciseAdapter
import com.example.fitnessapp.database.ExcerciseDatabase
import com.example.fitnessapp.databinding.FragmentExcercisesBinding


class ExcercisesFragment : Fragment() {

    private lateinit var binding: FragmentExcercisesBinding

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        binding = FragmentExcercisesBinding.inflate(layoutInflater)
        //val db = Room.databaseBuilder(requireContext(), ExcerciseDatabase::class.java, "excercisedatabase-db").allowMainThreadQueries().build()  //
        val db = Room.databaseBuilder(requireContext(), ExcerciseDatabase::class.java, "excercisedatabase-db").createFromAsset("databases/excercisedatabase-db.db").allowMainThreadQueries().build()
        val excerciseDao = db.excerciseDao()                                                                                                           //
        val excercises: MutableList<Excercise> = excerciseDao.getAll()                                                                                 // gets all database items and puts it in a list

        binding.rvwExcercises.adapter = ExcerciseAdapter(excercises)                                              // adds the excercises list in the recyclerview
        binding.rvwExcercises.layoutManager = LinearLayoutManager(context)                                        // chooses what type of layout
        binding.rvwExcercises.addItemDecoration(DividerItemDecoration(context, DividerItemDecoration.VERTICAL))   // this puts a line between every item

        binding.filter.addTextChangedListener(object : TextWatcher {                                //this is used to check the typed word which than filters the recyclerview to show to excercises that have a matching name or muscle group
            override fun beforeTextChanged(s: CharSequence, start: Int, count: Int, after: Int) {}
            override fun onTextChanged(s: CharSequence, start: Int, before: Int, count: Int) {}
            override fun afterTextChanged(s: Editable) {
                val filteredList: ArrayList<Excercise> = ArrayList()                          // local arraylist where the matches item are stored
                for (item in excercises) {                                                    // for loop checks for match with every item
                    if (item.name.lowercase().contains(s.toString().lowercase())) {           // name match check
                        filteredList.add(item)                                                //
                    }                                                                         //
                    if (item.muscleGroup.lowercase().contains(s.toString().lowercase())) {    // muscle group match check
                        filteredList.add(item)                                                //
                    }                                                                         //
                }                                                                             //
                binding.rvwExcercises.adapter = ExcerciseAdapter(filteredList)                // redraws the recyclerview
                binding.rvwExcercises.layoutManager = LinearLayoutManager(context)            //
            }                                                                                 //
        })                                                                                    //

        return binding.root
    }

}
























/*excerciseDao.insert(listOf(Excercise("ab crunch machine", " abdominals", 0),
            Excercise("ab roller", " abdominals", 0),
            Excercise("adductor", " adductors", 0),
            Excercise("adductor/groin", " adductors", 0),
            Excercise("advanced kettlebell windmill", " abdominals", 0),
            Excercise("air bike", " abdominals", 0),
            Excercise("all fours quad stretch", " quadriceps", 0),
            Excercise("alternate hammer curl", " biceps", 0),
            Excercise("alternate heel touchers", " abdominals", 0),
            Excercise("alternate incline dumbbell curl", " biceps", 0),
            Excercise("alternate leg diagonal bound", " quadriceps", 0),
            Excercise("alternating cable shoulder press", " shoulders", 0),
            Excercise("alternating deltoid raise", " shoulders", 0),
            Excercise("alternating floor press", " chest", 0),
            Excercise("alternating hang clean", " hamstrings", 0),
            Excercise("alternating kettlebell press", " shoulders", 0),
            Excercise("alternating kettlebell row", " middle back", 0),
            Excercise("alternating renegade row", " middle back", 0),
            Excercise("ankle circles", " calves", 0),
            Excercise("ankle on the knee", " glutes", 0),
            Excercise("anterior tibialis-smr", " calves", 0),
            Excercise("anti-gravity press", " shoulders", 0),
            Excercise("arm circles", " shoulders", 0),
            Excercise("arnold dumbbell press", " shoulders", 0),
            Excercise("around the worlds", " chest", 0),
            Excercise("atlas stone trainer", " lower back", 0),
            Excercise("atlas stones", " lower back", 0),
            Excercise("axle deadlift", " lower back", 0),
            Excercise("ab crunch machine", " abdominals", 0),
            Excercise("ab roller", " abdominals", 0),
            Excercise("adductor", " adductors", 0),
            Excercise("adductor/groin", " adductors", 0),
            Excercise("advanced kettlebell windmill", " abdominals", 0),
            Excercise("air bike", " abdominals", 0),
            Excercise("all fours quad stretch", " quadriceps", 0),
            Excercise("alternate hammer curl", " biceps", 0),
            Excercise("alternate heel touchers", " abdominals", 0),
            Excercise("alternate incline dumbbell curl", " biceps", 0),
            Excercise("alternate leg diagonal bound", " quadriceps", 0),
            Excercise("alternating cable shoulder press", " shoulders", 0),
            Excercise("alternating deltoid raise", " shoulders", 0),
            Excercise("alternating floor press", " chest", 0),
            Excercise("alternating hang clean", " hamstrings", 0),
            Excercise("alternating kettlebell press", " shoulders", 0),
            Excercise("alternating kettlebell row", " middle back", 0),
            Excercise("alternating renegade row", " middle back", 0),
            Excercise("ankle circles", " calves", 0),
            Excercise("ankle on the knee", " glutes", 0),
            Excercise("anterior tibialis-smr", " calves", 0),
            Excercise("anti-gravity press", " shoulders", 0),
            Excercise("arm circles", " shoulders", 0),
            Excercise("arnold dumbbell press", " shoulders", 0),
            Excercise("around the worlds", " chest", 0),
            Excercise("atlas stone trainer", " lower back", 0),
            Excercise("atlas stones", " lower back", 0),
            Excercise("axle deadlift", " lower back", 0),
            Excercise("back flyes - with bands", " shoulders", 0),
            Excercise("backward drag", " quadriceps", 0),
            Excercise("backward medicine ball throw", " shoulders", 0),
            Excercise("balance board", " calves", 0),
            Excercise("ball leg curl", " hamstrings", 0),
            Excercise("band assisted pull-up", " lats", 0),
            Excercise("band good morning", " hamstrings", 0),
            Excercise("band good morning (pull through)", " hamstrings", 0),
            Excercise("band hip adductions", " adductors", 0),
            Excercise("band pull apart", " shoulders", 0),
            Excercise("band skull crusher", " triceps", 0),
            Excercise("barbell ab rollout", " abdominals", 0),
            Excercise("barbell ab rollout - on knees", " abdominals", 0),
            Excercise("barbell bench press - medium grip", " chest", 0),
            Excercise("barbell curl", " biceps", 0),
            Excercise("barbell curls lying against an incline", " biceps", 0),
            Excercise("barbell deadlift", " lower back", 0),
            Excercise("barbell full squat", " quadriceps", 0),
            Excercise("barbell glute bridge", " glutes", 0),
            Excercise("barbell guillotine bench press", " chest", 0),
            Excercise("barbell hack squat", " quadriceps", 0),
            Excercise("barbell hip thrust", " glutes", 0),
            Excercise("barbell incline bench press - medium grip", " chest", 0),
            Excercise("barbell incline shoulder raise", " shoulders", 0),
            Excercise("barbell lunge", " quadriceps", 0),
            Excercise("barbell rear delt row", " shoulders", 0),
            Excercise("barbell rollout from bench", " abdominals", 0),
            Excercise("barbell seated calf raise", " calves", 0),
            Excercise("barbell shoulder press", " shoulders", 0),
            Excercise("barbell shrug", " traps", 0),
            Excercise("barbell shrug behind the back", " traps", 0),
            Excercise("barbell side bend", " abdominals", 0),
            Excercise("barbell side split squat", " quadriceps", 0),
            Excercise("barbell squat", " quadriceps", 0),
            Excercise("barbell squat to a bench", " quadriceps", 0),
            Excercise("barbell step ups", " quadriceps", 0),
            Excercise("barbell walking lunge", " quadriceps", 0),
            Excercise("battling ropes", " shoulders", 0),
            Excercise("bear crawl sled drags", " quadriceps", 0),
            Excercise("behind head chest stretch", " chest", 0),
            Excercise("bench dips", " triceps", 0),
            Excercise("bench jump", " quadriceps", 0),
            Excercise("bench press - powerlifting", " triceps", 0),
            Excercise("bench press - with bands", " chest", 0),
            Excercise("bench press with chains", " triceps", 0),
            Excercise("bench sprint", " quadriceps", 0),
            Excercise("bent over barbell row", " middle back", 0),
            Excercise("bent over dumbbell rear delt raise with head on bench", " shoulders", 0),
            Excercise("bent over low-pulley side lateral", " shoulders", 0),
            Excercise("bent over one-arm long bar row", " middle back", 0),
            Excercise("bent over two-arm long bar row", " middle back", 0),
            Excercise("bent over two-dumbbell row", " middle back", 0),
            Excercise("bent over two-dumbbell row with palms in", " middle back", 0),
            Excercise("bent press", " abdominals", 0),
            Excercise("bent-arm barbell pullover", " lats", 0),
            Excercise("bent-arm dumbbell pullover", " chest", 0),
            Excercise("bent-knee hip raise", " abdominals", 0),
            Excercise("bicycling", " quadriceps", 0),
            Excercise("bicycling", " stationary", 0),
            Excercise("board press", " triceps", 0),
            Excercise("body tricep press", " triceps", 0),
            Excercise("body-up", " triceps", 0),
            Excercise("bodyweight flyes", " chest", 0),
            Excercise("bodyweight mid row", " middle back", 0),
            Excercise("bodyweight squat", " quadriceps", 0),
            Excercise("bodyweight walking lunge", " quadriceps", 0),
            Excercise("bosu ball cable crunch with side bends", " abdominals", 0),
            Excercise("bottoms up", " abdominals", 0),
            Excercise("bottoms-up clean from the hang position", " forearms", 0),
            Excercise("box jump (multiple response)", " hamstrings", 0),
            Excercise("box skip", " hamstrings", 0),
            Excercise("box squat", " quadriceps", 0),
            Excercise("box squat with bands", " quadriceps", 0),
            Excercise("box squat with chains", " quadriceps", 0),
            Excercise("brachialis-smr", " biceps", 0),
            Excercise("bradford/rocky presses", " shoulders", 0),
            Excercise("butt lift (bridge)", " glutes", 0),
            Excercise("butt-ups", " abdominals", 0),
            Excercise("butterfly", " chest", 0),
            Excercise("cable chest press", " chest", 0),
            Excercise("cable crossover", " chest", 0),
            Excercise("cable crunch", " abdominals", 0),
            Excercise("cable deadlifts", " quadriceps", 0),
            Excercise("cable hammer curls - rope attachment", " biceps", 0),
            Excercise("cable hip adduction", " quadriceps", 0),
            Excercise("cable incline pushdown", " lats", 0),
            Excercise("cable incline triceps extension", " triceps", 0),
            Excercise("cable internal rotation", " shoulders", 0),
            Excercise("cable iron cross", " chest", 0),
            Excercise("cable judo flip", " abdominals", 0),
            Excercise("cable lying triceps extension", " triceps", 0),
            Excercise("cable one arm tricep extension", " triceps", 0),
            Excercise("cable preacher curl", " biceps", 0),
            Excercise("cable rear delt fly", " shoulders", 0),
            Excercise("cable reverse crunch", " abdominals", 0),
            Excercise("cable rope overhead triceps extension", " triceps", 0),
            Excercise("cable rope rear-delt rows", " shoulders", 0),
            Excercise("cable russian twists", " abdominals", 0),
            Excercise("cable seated crunch", " abdominals", 0),
            Excercise("cable seated lateral raise", " shoulders", 0),
            Excercise("cable shoulder press", " shoulders", 0),
            Excercise("cable shrugs", " traps", 0),
            Excercise("cable tuck reverse crunch", " abdominals", 0),
            Excercise("cable wrist curl", " forearms", 0),
            Excercise("calf press", " calves", 0),
            Excercise("calf press on the leg press machine", " calves", 0),
            Excercise("calf raise on a dumbbell", " calves", 0),
            Excercise("calf raises - with bands", " calves", 0),
            Excercise("calf stretch elbows against wall", " calves", 0),
            Excercise("calf stretch hands against wall", " calves", 0),
            Excercise("calf-machine shoulder shrug", " traps", 0),
            Excercise("calves-smr", " calves", 0),
            Excercise("car deadlift", " quadriceps", 0),
            Excercise("car drivers", " shoulders", 0),
            Excercise("carioca quick step", " adductors", 0),
            Excercise("cat stretch", " lower back", 0),
            Excercise("catch and overhead throw", " lats", 0),
            Excercise("chain handle extension", " triceps", 0),
            Excercise("chain press", " chest", 0),
            Excercise("chair leg extended stretch", " hamstrings", 0),
            Excercise("chair lower back stretch", " lats", 0),
            Excercise("chair squat", " quadriceps", 0),
            Excercise("chair upper body stretch", " shoulders", 0),
            Excercise("chest and front of shoulder stretch", " chest", 0),
            Excercise("chest push (multiple response)", " chest", 0),
            Excercise("chest push (single response)", " chest", 0),
            Excercise("chest push from 3 point stance", " chest", 0),
            Excercise("chest push with run release", " chest", 0),
            Excercise("chest stretch on stability ball", " chest", 0),
            Excercise("child's pose", " lower back", 0),
            Excercise("chin to chest stretch", " neck", 0),
            Excercise("chin-up", " lats", 0),
            Excercise("circus bell", " shoulders", 0),
            Excercise("clean", " hamstrings", 0),
            Excercise("clean and jerk", " shoulders", 0),
            Excercise("clean and press", " shoulders", 0),
            Excercise("clean deadlift", " hamstrings", 0),
            Excercise("clean from blocks", " quadriceps", 0),
            Excercise("clean pull", " quadriceps", 0),
            Excercise("clean shrug", " traps", 0),
            Excercise("clock push-up", " chest", 0),
            Excercise("close-grip barbell bench press", " triceps", 0),
            Excercise("close-grip dumbbell press", " triceps", 0),
            Excercise("close-grip ez bar curl", " biceps", 0),
            Excercise("close-grip ez-bar curl with band", " biceps", 0),
            Excercise("close-grip ez-bar press", " triceps", 0),
            Excercise("close-grip front lat pulldown", " lats", 0),
            Excercise("close-grip push-up off of a dumbbell", " triceps", 0),
            Excercise("close-grip standing barbell curl", " biceps", 0),
            Excercise("cocoons", " abdominals", 0),
            Excercise("conan's wheel", " quadriceps", 0),
            Excercise("concentration curls", " biceps", 0),
            Excercise("cross body hammer curl", " biceps", 0),
            Excercise("cross over - with bands", " chest", 0),
            Excercise("cross-body crunch", " abdominals", 0),
            Excercise("crossover reverse lunge", " lower back", 0),
            Excercise("crucifix", " shoulders", 0),
            Excercise("crunch - hands overhead", " abdominals", 0),
            Excercise("crunch - legs on exercise ball", " abdominals", 0),
            Excercise("crunches", " abdominals", 0),
            Excercise("cuban press", " shoulders", 0),
            Excercise("dancer's stretch", " lower back", 0),
            Excercise("deadlift with bands", " lower back", 0),
            Excercise("deadlift with chains", " lower back", 0),
            Excercise("decline barbell bench press", " chest", 0),
            Excercise("decline close-grip bench to skull crusher", " triceps", 0),
            Excercise("decline crunch", " abdominals", 0),
            Excercise("decline dumbbell bench press", " chest", 0),
            Excercise("decline dumbbell flyes", " chest", 0),
            Excercise("decline dumbbell triceps extension", " triceps", 0),
            Excercise("decline ez bar triceps extension", " triceps", 0),
            Excercise("decline oblique crunch", " abdominals", 0),
            Excercise("decline push-up", " chest", 0),
            Excercise("decline reverse crunch", " abdominals", 0),
            Excercise("decline smith press", " chest", 0),
            Excercise("deficit deadlift", " lower back", 0),
            Excercise("depth jump leap", " quadriceps", 0),
            Excercise("dip machine", " triceps", 0),
            Excercise("dips - chest version", " chest", 0),
            Excercise("dips - triceps version", " triceps", 0),
            Excercise("donkey calf raises", " calves", 0),
            Excercise("double kettlebell alternating hang clean", " hamstrings", 0),
            Excercise("double kettlebell jerk", " shoulders", 0),
            Excercise("double kettlebell push press", " shoulders", 0),
            Excercise("double kettlebell snatch", " shoulders", 0),
            Excercise("double kettlebell windmill", " abdominals", 0),
            Excercise("double leg butt kick", " quadriceps", 0),
            Excercise("downward facing balance", " glutes", 0),
            Excercise("drag curl", " biceps", 0),
            Excercise("drop push", " chest", 0),
            Excercise("dumbbell alternate bicep curl", " biceps", 0),
            Excercise("dumbbell bench press", " chest", 0),
            Excercise("dumbbell bench press with neutral grip", " chest", 0),
            Excercise("dumbbell bicep curl", " biceps", 0),
            Excercise("dumbbell clean", " hamstrings", 0),
            Excercise("dumbbell floor press", " triceps", 0),
            Excercise("dumbbell flyes", " chest", 0),
            Excercise("dumbbell incline row", " middle back", 0),
            Excercise("dumbbell incline shoulder raise", " shoulders", 0),
            Excercise("dumbbell lunges", " quadriceps", 0),
            Excercise("dumbbell lying one-arm rear lateral raise", " shoulders", 0),
            Excercise("dumbbell lying pronation", " forearms", 0),
            Excercise("dumbbell lying rear lateral raise", " shoulders", 0),
            Excercise("dumbbell lying supination", " forearms", 0),
            Excercise("dumbbell one-arm shoulder press", " shoulders", 0),
            Excercise("dumbbell one-arm triceps extension", " triceps", 0),
            Excercise("dumbbell one-arm upright row", " shoulders", 0),
            Excercise("dumbbell prone incline curl", " biceps", 0),
            Excercise("dumbbell raise", " shoulders", 0),
            Excercise("dumbbell rear lunge", " quadriceps", 0),
            Excercise("dumbbell scaption", " shoulders", 0),
            Excercise("dumbbell seated box jump", " quadriceps", 0),
            Excercise("dumbbell seated one-leg calf raise", " calves", 0),
            Excercise("dumbbell shoulder press", " shoulders", 0),
            Excercise("dumbbell shrug", " traps", 0),
            Excercise("dumbbell side bend", " abdominals", 0),
            Excercise("dumbbell squat", " quadriceps", 0),
            Excercise("dumbbell squat to a bench", " quadriceps", 0),
            Excercise("dumbbell step ups", " quadriceps", 0),
            Excercise("dumbbell tricep extension -pronated grip", " triceps", 0),
            Excercise("dynamic back stretch", " lats", 0),
            Excercise("dynamic chest stretch", " chest", 0),
            Excercise("elbow circles", " shoulders", 0),
            Excercise("elbow to knee", " abdominals", 0),
            Excercise("elbows back", " chest", 0),
            Excercise("elevated back lunge", " quadriceps", 0),
            Excercise("elevated cable rows", " lats", 0),
            Excercise("elliptical trainer", " quadriceps", 0),
            Excercise("exercise ball crunch", " abdominals", 0),
            Excercise("exercise ball pull-in", " abdominals", 0),
            Excercise("extended range one-arm kettlebell floor press", " chest", 0),
            Excercise("external rotation", " shoulders", 0),
            Excercise("external rotation with band", " shoulders", 0),
            Excercise("external rotation with cable", " shoulders", 0),
            Excercise("ez-bar curl", " biceps", 0),
            Excercise("ez-bar skullcrusher", " triceps", 0),
            Excercise("face pull", " shoulders", 0),
            Excercise("farmer's walk", " forearms", 0),
            Excercise("fast skipping", " quadriceps", 0),
            Excercise("finger curls", " forearms", 0),
            Excercise("flat bench cable flyes", " chest", 0),
            Excercise("flat bench leg pull-in", " abdominals", 0),
            Excercise("flat bench lying leg raise", " abdominals", 0),
            Excercise("flexor incline dumbbell curls", " biceps", 0),
            Excercise("floor glute-ham raise", " hamstrings", 0),
            Excercise("floor press", " triceps", 0),
            Excercise("floor press with chains", " triceps", 0),
            Excercise("flutter kicks", " glutes", 0),
            Excercise("foot-smr", " calves", 0),
            Excercise("forward drag with press", " chest", 0),
            Excercise("frankenstein squat", " quadriceps", 0),
            Excercise("freehand jump squat", " quadriceps", 0),
            Excercise("frog hops", " quadriceps", 0),
            Excercise("frog sit-ups", " abdominals", 0),
            Excercise("front barbell squat", " quadriceps", 0),
            Excercise("front barbell squat to a bench", " quadriceps", 0),
            Excercise("front box jump", " hamstrings", 0),
            Excercise("front cable raise", " shoulders", 0),
            Excercise("front cone hops (or hurdle hops)", " quadriceps", 0),
            Excercise("front dumbbell raise", " shoulders", 0),
            Excercise("front incline dumbbell raise", " shoulders", 0),
            Excercise("front leg raises", " hamstrings", 0),
            Excercise("front plate raise", " shoulders", 0),
            Excercise("front raise and pullover", " chest", 0),
            Excercise("front squat (clean grip)", " quadriceps", 0),
            Excercise("front squats with two kettlebells", " quadriceps", 0),
            Excercise("front two-dumbbell raise", " shoulders", 0),
            Excercise("full range-of-motion lat pulldown", " lats", 0),
            Excercise("gironda sternum chins", " lats", 0),
            Excercise("glute ham raise", " hamstrings", 0),
            Excercise("glute kickback", " glutes", 0),
            Excercise("goblet squat", " quadriceps", 0),
            Excercise("good morning", " hamstrings", 0),
            Excercise("good morning off pins", " hamstrings", 0),
            Excercise("gorilla chin/crunch", " abdominals", 0),
            Excercise("groin and back stretch", " adductors", 0),
            Excercise("groiners", " adductors", 0),
            Excercise("hack squat", " quadriceps", 0),
            Excercise("hammer curls", " biceps", 0),
            Excercise("hammer grip incline db bench press", " chest", 0),
            Excercise("hamstring stretch", " hamstrings", 0),
            Excercise("hamstring-smr", " hamstrings", 0),
            Excercise("handstand push-ups", " shoulders", 0),
            Excercise("hang clean", " quadriceps", 0),
            Excercise("hang clean - below the knees", " quadriceps", 0),
            Excercise("hang snatch", " hamstrings", 0),
            Excercise("hang snatch - below knees", " hamstrings", 0),
            Excercise("hanging bar good morning", " hamstrings", 0),
            Excercise("hanging leg raise", " abdominals", 0),
            Excercise("hanging pike", " abdominals", 0),
            Excercise("heaving snatch balance", " quadriceps", 0),
            Excercise("heavy bag thrust", " chest", 0),
            Excercise("high cable curls", " biceps", 0),
            Excercise("hip circles (prone)", " abductors", 0),
            Excercise("hip crossover", "", 0),
            Excercise("hip extension with bands", " glutes", 0),
            Excercise("hip flexion with band", " quadriceps", 0),
            Excercise("hip lift with band", " glutes", 0),
            Excercise("hug a ball", " lower back", 0),
            Excercise("hug knees to chest", " lower back", 0),
            Excercise("hurdle hops", " hamstrings", 0),
            Excercise("hyperextensions (back extensions)", " lower back", 0),
            Excercise("hyperextensions with no hyperextension bench", " lower back", 0),
            Excercise("iliotibial tract-smr", " abductors", 0),
            Excercise("incline barbell triceps extension", " triceps", 0),
            Excercise("incline bench pull", " middle back", 0),
            Excercise("incline cable chest press", " chest", 0),
            Excercise("incline cable flye", " chest", 0),
            Excercise("incline dumbbell bench with palms facing in", " chest", 0),
            Excercise("incline dumbbell curl", " biceps", 0),
            Excercise("incline dumbbell flyes", " chest", 0),
            Excercise("incline dumbbell flyes - with a twist", " chest", 0),
            Excercise("incline dumbbell press", " chest", 0),
            Excercise("incline hammer curls", " biceps", 0),
            Excercise("incline inner biceps curl", " biceps", 0),
            Excercise("incline push-up", " chest", 0),
            Excercise("incline push-up close-grip", " triceps", 0),
            Excercise("incline push-up depth jump", " chest", 0),
            Excercise("incline push-up medium", " chest", 0),
            Excercise("incline push-up reverse grip", " chest", 0),
            Excercise("incline push-up wide", " chest", 0),
            Excercise("intermediate groin stretch", " hamstrings", 0),
            Excercise("intermediate hip flexor and quad stretch", " quadriceps", 0),
            Excercise("internal rotation with band", " shoulders", 0),
            Excercise("inverted row", " middle back", 0),
            Excercise("inverted row with straps", " middle back", 0),
            Excercise("iron cross", " shoulders", 0),
            Excercise("iron crosses (stretch)", " quadriceps", 0),
            Excercise("isometric chest squeezes", " chest", 0),
            Excercise("isometric neck exercise - front and back", " neck", 0),
            Excercise("isometric neck exercise - sides", " neck", 0),
            Excercise("isometric wipers", " chest", 0),
            Excercise("it band and glute stretch", " abductors", 0),
            Excercise("jackknife sit-up", " abdominals", 0),
            Excercise("janda sit-up", " abdominals", 0),
            Excercise("jefferson squats", " quadriceps", 0),
            Excercise("jerk balance", " shoulders", 0),
            Excercise("jerk dip squat", " quadriceps", 0),
            Excercise("jm press", " triceps", 0),
            Excercise("jogging-treadmill", " quadriceps", 0),
            Excercise("keg load", " lower back", 0),
            Excercise("kettlebell arnold press", " shoulders", 0),
            Excercise("kettlebell dead clean", " hamstrings", 0),
            Excercise("kettlebell figure 8", " abdominals", 0),
            Excercise("kettlebell hang clean", " hamstrings", 0),
            Excercise("kettlebell one-legged deadlift", " hamstrings", 0),
            Excercise("kettlebell pass between the legs", " abdominals", 0),
            Excercise("kettlebell pirate ships", " shoulders", 0),
            Excercise("kettlebell pistol squat", " quadriceps", 0),
            Excercise("kettlebell seated press", " shoulders", 0),
            Excercise("kettlebell seesaw press", " shoulders", 0),
            Excercise("kettlebell sumo high pull", " traps", 0),
            Excercise("kettlebell thruster", " shoulders", 0),
            Excercise("kettlebell turkish get-up (lunge style)", " shoulders", 0),
            Excercise("kettlebell turkish get-up (squat style)", " shoulders", 0),
            Excercise("kettlebell windmill", " abdominals", 0),
            Excercise("kipping muscle up", " lats", 0),
            Excercise("knee across the body", " glutes", 0),
            Excercise("knee circles", " calves", 0),
            Excercise("knee tuck jump", " hamstrings", 0),
            Excercise("knee/hip raise on parallel bars", " abdominals", 0),
            Excercise("kneeling arm drill", " shoulders", 0),
            Excercise("kneeling cable crunch with alternating oblique twists", " abdominals", 0),
            Excercise("kneeling cable triceps extension", " triceps", 0),
            Excercise("kneeling forearm stretch", " forearms", 0),
            Excercise("kneeling high pulley row", " lats", 0),
            Excercise("kneeling hip flexor", " quadriceps", 0),
            Excercise("kneeling jump squat", " glutes", 0),
            Excercise("kneeling single-arm high pulley row", " lats", 0),
            Excercise("kneeling squat", " glutes", 0),
            Excercise("landmine 180's", " abdominals", 0),
            Excercise("landmine linear jammer", " shoulders", 0),
            Excercise("lateral bound", " adductors", 0),
            Excercise("lateral box jump", " adductors", 0),
            Excercise("lateral cone hops", " adductors", 0),
            Excercise("lateral raise - with bands", " shoulders", 0),
            Excercise("latissimus dorsi-smr", " lats", 0),
            Excercise("leg extensions", " quadriceps", 0),
            Excercise("leg lift", " glutes", 0),
            Excercise("leg press", " quadriceps", 0),
            Excercise("leg pull-in", " abdominals", 0),
            Excercise("leg-over floor press", " chest", 0),
            Excercise("leg-up hamstring stretch", " hamstrings", 0),
            Excercise("leverage chest press", " chest", 0),
            Excercise("leverage deadlift", " quadriceps", 0),
            Excercise("leverage decline chest press", " chest", 0),
            Excercise("leverage high row", " middle back", 0),
            Excercise("leverage incline chest press", " chest", 0),
            Excercise("leverage iso row", " lats", 0),
            Excercise("leverage shoulder press", " shoulders", 0),
            Excercise("leverage shrug", " traps", 0),
            Excercise("linear 3-part start technique", " hamstrings", 0),
            Excercise("linear acceleration wall drill", " hamstrings", 0),
            Excercise("linear depth jump", " quadriceps", 0),
            Excercise("log lift", " shoulders", 0),
            Excercise("london bridges", " lats", 0),
            Excercise("looking at ceiling", " quadriceps", 0),
            Excercise("low cable crossover", " chest", 0),
            Excercise("low cable triceps extension", " triceps", 0),
            Excercise("low pulley row to neck", " shoulders", 0),
            Excercise("lower back curl", " abdominals", 0),
            Excercise("lower back-smr", " lower back", 0),
            Excercise("lunge pass through", " hamstrings", 0),
            Excercise("lunge sprint", " quadriceps", 0),
            Excercise("lying bent leg groin", " adductors", 0),
            Excercise("lying cable curl", " biceps", 0),
            Excercise("lying cambered barbell row", " middle back", 0),
            Excercise("lying close-grip bar curl on high pulley", " biceps", 0),
            Excercise("lying close-grip barbell triceps extension behind the head", " triceps", 0),
            Excercise("lying close-grip barbell triceps press to chin", " triceps", 0),
            Excercise("lying crossover", " abductors", 0),
            Excercise("lying dumbbell tricep extension", " triceps", 0),
            Excercise("lying face down plate neck resistance", " neck", 0),
            Excercise("lying face up plate neck resistance", " neck", 0),
            Excercise("lying glute", " glutes", 0),
            Excercise("lying hamstring", " hamstrings", 0),
            Excercise("lying high bench barbell curl", " biceps", 0),
            Excercise("lying leg curls", " hamstrings", 0),
            Excercise("lying machine squat", " quadriceps", 0),
            Excercise("lying one-arm lateral raise", " shoulders", 0),
            Excercise("lying prone quadriceps", " quadriceps", 0),
            Excercise("lying rear delt raise", " shoulders", 0),
            Excercise("lying supine dumbbell curl", " biceps", 0),
            Excercise("lying t-bar row", " middle back", 0),
            Excercise("lying triceps press", " triceps", 0),
            Excercise("machine bench press", " chest", 0),
            Excercise("machine bicep curl", " biceps", 0),
            Excercise("machine preacher curls", " biceps", 0),
            Excercise("machine shoulder (military) press", " shoulders", 0),
            Excercise("machine triceps extension", " triceps", 0),
            Excercise("medicine ball chest pass", " chest", 0),
            Excercise("medicine ball full twist", " abdominals", 0),
            Excercise("medicine ball scoop throw", " shoulders", 0),
            Excercise("middle back shrug", " middle back", 0),
            Excercise("middle back stretch", " middle back", 0),
            Excercise("mixed grip chin", " middle back", 0),
            Excercise("monster walk", " abductors", 0),
            Excercise("mountain climbers", " quadriceps", 0),
            Excercise("moving claw series", " hamstrings", 0),
            Excercise("muscle snatch", " hamstrings", 0),
            Excercise("muscle up", " lats", 0),
            Excercise("narrow stance hack squats", " quadriceps", 0),
            Excercise("narrow stance leg press", " quadriceps", 0),
            Excercise("narrow stance squats", " quadriceps", 0),
            Excercise("natural glute ham raise", " hamstrings", 0),
            Excercise("neck press", " chest", 0),
            Excercise("neck-smr", " neck", 0),
            Excercise("oblique crunches", " abdominals", 0),
            Excercise("oblique crunches - on the floor", " abdominals", 0),
            Excercise("olympic squat", " quadriceps", 0),
            Excercise("on your side quad stretch", " quadriceps", 0),
            Excercise("on-your-back quad stretch", " quadriceps", 0),
            Excercise("one arm against wall", " lats", 0),
            Excercise("one arm chin-up", " middle back", 0),
            Excercise("one arm dumbbell bench press", " chest", 0),
            Excercise("one arm dumbbell preacher curl", " biceps", 0),
            Excercise("one arm floor press", " triceps", 0),
            Excercise("one arm lat pulldown", " lats", 0),
            Excercise("one arm pronated dumbbell triceps extension", " triceps", 0),
            Excercise("one arm supinated dumbbell triceps extension", " triceps", 0),
            Excercise("one half locust", " quadriceps", 0),
            Excercise("one handed hang", " lats", 0),
            Excercise("one knee to chest", " glutes", 0),
            Excercise("one leg barbell squat", " quadriceps", 0),
            Excercise("one-arm dumbbell row", " middle back", 0),
            Excercise("one-arm flat bench dumbbell flye", " chest", 0),
            Excercise("one-arm high-pulley cable side bends", " abdominals", 0),
            Excercise("one-arm incline lateral raise", " shoulders", 0),
            Excercise("one-arm kettlebell clean", " hamstrings", 0),
            Excercise("one-arm kettlebell clean and jerk", " shoulders", 0),
            Excercise("one-arm kettlebell floor press", " chest", 0),
            Excercise("one-arm kettlebell jerk", " shoulders", 0),
            Excercise("one-arm kettlebell military press to the side", " shoulders", 0),
            Excercise("one-arm kettlebell para press", " shoulders", 0),
            Excercise("one-arm kettlebell push press", " shoulders", 0),
            Excercise("one-arm kettlebell row", " middle back", 0),
            Excercise("one-arm kettlebell snatch", " shoulders", 0),
            Excercise("one-arm kettlebell split jerk", " shoulders", 0),
            Excercise("one-arm kettlebell split snatch", " shoulders", 0),
            Excercise("one-arm kettlebell swings", " hamstrings", 0),
            Excercise("one-arm long bar row", " middle back", 0),
            Excercise("one-arm medicine ball slam", " abdominals", 0),
            Excercise("one-arm open palm kettlebell clean", " hamstrings", 0),
            Excercise("one-arm overhead kettlebell squats", " quadriceps", 0),
            Excercise("one-arm side deadlift", " quadriceps", 0),
            Excercise("one-arm side laterals", " shoulders", 0),
            Excercise("one-legged cable kickback", " glutes", 0),
            Excercise("open palm kettlebell clean", " hamstrings", 0),
            Excercise("otis-up", " abdominals", 0),
            Excercise("overhead cable curl", " biceps", 0),
            Excercise("overhead lat", " lats", 0),
            Excercise("overhead slam", " lats", 0),
            Excercise("overhead squat", " quadriceps", 0),
            Excercise("overhead stretch", " abdominals", 0),
            Excercise("overhead triceps", " triceps", 0),
            Excercise("pallof press with rotation", " abdominals", 0),
            Excercise("palms-down dumbbell wrist curl over a bench", " forearms", 0),
            Excercise("palms-down wrist curl over a bench", " forearms", 0),
            Excercise("palms-up barbell wrist curl over a bench", " forearms", 0),
            Excercise("palms-up dumbbell wrist curl over a bench", " forearms", 0),
            Excercise("parallel bar dip", " triceps", 0),
            Excercise("pelvic tilt into bridge", " lower back", 0),
            Excercise("peroneals stretch", " calves", 0),
            Excercise("peroneals-smr", " calves", 0),
            Excercise("physioball hip bridge", " glutes", 0),
            Excercise("pin presses", " triceps", 0),
            Excercise("piriformis-smr", " glutes", 0),
            Excercise("plank", " abdominals", 0),
            Excercise("plank with twist", "", 0),
            Excercise("plate pinch", " forearms", 0),
            Excercise("plate twist", " abdominals", 0),
            Excercise("platform hamstring slides", " hamstrings", 0),
            Excercise("plie dumbbell squat", " quadriceps", 0),
            Excercise("plyo kettlebell pushups", " chest", 0),
            Excercise("plyo push-up", " chest", 0),
            Excercise("posterior tibialis stretch", " calves", 0),
            Excercise("power clean", " hamstrings", 0),
            Excercise("power clean from blocks", " hamstrings", 0),
            Excercise("power jerk", " quadriceps", 0),
            Excercise("power partials", " shoulders", 0),
            Excercise("power snatch", " hamstrings", 0),
            Excercise("power snatch from blocks", " quadriceps", 0),
            Excercise("power stairs", " hamstrings", 0),
            Excercise("preacher curl", " biceps", 0),
            Excercise("preacher hammer dumbbell curl", " biceps", 0),
            Excercise("press sit-up", " abdominals", 0),
            Excercise("prone manual hamstring", " hamstrings", 0),
            Excercise("prowler sprint", " hamstrings", 0),
            Excercise("pull through", " glutes", 0),
            Excercise("pullups", " lats", 0),
            Excercise("push press", " shoulders", 0),
            Excercise("push press - behind the neck", " shoulders", 0),
            Excercise("push up to side plank", " chest", 0),
            Excercise("push-up wide", " chest", 0),
            Excercise("push-ups - close triceps position", " triceps", 0),
            Excercise("push-ups with feet elevated", " chest", 0),
            Excercise("push-ups with feet on an exercise ball", " chest", 0),
            Excercise("pushups", " chest", 0),
            Excercise("pushups (close and wide hand positions)", " chest", 0),
            Excercise("pyramid", " lower back", 0),
            Excercise("quad stretch", " quadriceps", 0),
            Excercise("quadriceps-smr", " quadriceps", 0),
            Excercise("quick leap", " quadriceps", 0),
            Excercise("rack delivery", " shoulders", 0),
            Excercise("rack pull with bands", " lower back", 0),
            Excercise("rack pulls", " lower back", 0),
            Excercise("rear leg raises", " quadriceps", 0),
            Excercise("recumbent bike", " quadriceps", 0),
            Excercise("return push from stance", " shoulders", 0),
            Excercise("reverse band bench press", " triceps", 0),
            Excercise("reverse band box squat", " quadriceps", 0),
            Excercise("reverse band deadlift", " lower back", 0),
            Excercise("reverse band power squat", " quadriceps", 0),
            Excercise("reverse band sumo deadlift", " hamstrings", 0),
            Excercise("reverse barbell curl", " biceps", 0),
            Excercise("reverse barbell preacher curls", " biceps", 0),
            Excercise("reverse cable curl", " biceps", 0),
            Excercise("reverse crunch", " abdominals", 0),
            Excercise("reverse flyes", " shoulders", 0),
            Excercise("reverse flyes with external rotation", " shoulders", 0),
            Excercise("reverse grip bent-over rows", " middle back", 0),
            Excercise("reverse grip triceps pushdown", " triceps", 0),
            Excercise("reverse hyperextension", " hamstrings", 0),
            Excercise("reverse machine flyes", " shoulders", 0),
            Excercise("reverse plate curls", " biceps", 0),
            Excercise("reverse triceps bench press", " triceps", 0),
            Excercise("rhomboids-smr", " middle back", 0),
            Excercise("rickshaw carry", " forearms", 0),
            Excercise("rickshaw deadlift", " quadriceps", 0),
            Excercise("ring dips", " triceps", 0),
            Excercise("rocket jump", " quadriceps", 0),
            Excercise("rocking standing calf raise", " calves", 0),
            Excercise("rocky pull-ups/pulldowns", " lats", 0),
            Excercise("romanian deadlift", " hamstrings", 0),
            Excercise("romanian deadlift from deficit", " hamstrings", 0),
            Excercise("rope climb", " lats", 0),
            Excercise("rope crunch", " abdominals", 0),
            Excercise("rope jumping", " quadriceps", 0),
            Excercise("rope straight-arm pulldown", " lats", 0),
            Excercise("round the world shoulder stretch", " shoulders", 0),
            Excercise("rowing", " stationary", 0),
            Excercise("runner's stretch", " hamstrings", 0),
            Excercise("running", " treadmill", 0),
            Excercise("russian twist", " abdominals", 0),
            Excercise("sandbag load", " quadriceps", 0),
            Excercise("scapular pull-up", " traps", 0),
            Excercise("scissor kick", " abdominals", 0),
            Excercise("scissors jump", " quadriceps", 0),
            Excercise("seated band hamstring curl", " hamstrings", 0),
            Excercise("seated barbell military press", " shoulders", 0),
            Excercise("seated barbell twist", " abdominals", 0),
            Excercise("seated bent-over one-arm dumbbell triceps extension", " triceps", 0),
            Excercise("seated bent-over rear delt raise", " shoulders", 0),
            Excercise("seated bent-over two-arm dumbbell triceps extension", " triceps", 0),
            Excercise("seated biceps", " biceps", 0),
            Excercise("seated cable rows", " middle back", 0),
            Excercise("seated cable shoulder press", " shoulders", 0),
            Excercise("seated calf raise", " calves", 0),
            Excercise("seated calf stretch", " calves", 0),
            Excercise("seated close-grip concentration barbell curl", " biceps", 0),
            Excercise("seated dumbbell curl", " biceps", 0),
            Excercise("seated dumbbell inner biceps curl", " biceps", 0),
            Excercise("seated dumbbell palms-down wrist curl", " forearms", 0),
            Excercise("seated dumbbell palms-up wrist curl", " forearms", 0),
            Excercise("seated dumbbell press", " shoulders", 0),
            Excercise("seated flat bench leg pull-in", " abdominals", 0),
            Excercise("seated floor hamstring stretch", " hamstrings", 0),
            Excercise("seated front deltoid", " shoulders", 0),
            Excercise("seated glute", " glutes", 0),
            Excercise("seated good mornings", " lower back", 0),
            Excercise("seated hamstring", " hamstrings", 0),
            Excercise("seated hamstring and calf stretch", " hamstrings", 0),
            Excercise("seated head harness neck resistance", " neck", 0),
            Excercise("seated leg curl", " hamstrings", 0),
            Excercise("seated leg tucks", " abdominals", 0),
            Excercise("seated one-arm cable pulley rows", " middle back", 0),
            Excercise("seated one-arm dumbbell palms-down wrist curl", " forearms", 0),
            Excercise("seated one-arm dumbbell palms-up wrist curl", " forearms", 0),
            Excercise("seated overhead stretch", " abdominals", 0),
            Excercise("seated palm-up barbell wrist curl", " forearms", 0),
            Excercise("seated palms-down barbell wrist curl", " forearms", 0),
            Excercise("seated side lateral raise", " shoulders", 0),
            Excercise("seated triceps press", " triceps", 0),
            Excercise("seated two-arm palms-up low-pulley wrist curl", " forearms", 0),
            Excercise("see-saw press (alternating side press)", " shoulders", 0),
            Excercise("shotgun row", " lats", 0),
            Excercise("shoulder circles", " shoulders", 0),
            Excercise("shoulder press - with bands", " shoulders", 0),
            Excercise("shoulder raise", " shoulders", 0),
            Excercise("shoulder stretch", " shoulders", 0),
            Excercise("side bridge", " abdominals", 0),
            Excercise("side hop-sprint", " quadriceps", 0),
            Excercise("side jackknife", " abdominals", 0),
            Excercise("side lateral raise", " shoulders", 0),
            Excercise("side laterals to front raise", " shoulders", 0),
            Excercise("side leg raises", " adductors", 0),
            Excercise("side lying groin stretch", " adductors", 0),
            Excercise("side neck stretch", " neck", 0),
            Excercise("side standing long jump", " quadriceps", 0),
            Excercise("side to side box shuffle", " quadriceps", 0),
            Excercise("side to side chins", " lats", 0),
            Excercise("side wrist pull", " shoulders", 0),
            Excercise("side-lying floor stretch", " lats", 0),
            Excercise("single dumbbell raise", " shoulders", 0),
            Excercise("single leg butt kick", " quadriceps", 0),
            Excercise("single leg glute bridge", " glutes", 0),
            Excercise("single leg push-off", " quadriceps", 0),
            Excercise("single-arm cable crossover", " chest", 0),
            Excercise("single-arm linear jammer", " shoulders", 0),
            Excercise("single-arm push-up", " chest", 0),
            Excercise("single-cone sprint drill", " quadriceps", 0),
            Excercise("single-leg high box squat", " quadriceps", 0),
            Excercise("single-leg hop progression", " quadriceps", 0),
            Excercise("single-leg lateral hop", " quadriceps", 0),
            Excercise("single-leg leg extension", " quadriceps", 0),
            Excercise("single-leg stride jump", " quadriceps", 0),
            Excercise("sit squats", " quadriceps", 0),
            Excercise("sit-up", " abdominals", 0),
            Excercise("skating", " quadriceps", 0),
            Excercise("sled drag - harness", " quadriceps", 0),
            Excercise("sled overhead backward walk", " shoulders", 0),
            Excercise("sled overhead triceps extension", " triceps", 0),
            Excercise("sled push", " quadriceps", 0),
            Excercise("sled reverse flye", " shoulders", 0),
            Excercise("sled row", " middle back", 0),
            Excercise("sledgehammer swings", " abdominals", 0),
            Excercise("smith incline shoulder raise", " shoulders", 0),
            Excercise("smith machine behind the back shrug", " traps", 0),
            Excercise("smith machine bench press", " chest", 0),
            Excercise("smith machine bent over row", " middle back", 0),
            Excercise("smith machine calf raise", " calves", 0),
            Excercise("smith machine close-grip bench press", " triceps", 0),
            Excercise("smith machine decline press", " chest", 0),
            Excercise("smith machine hang power clean", " hamstrings", 0),
            Excercise("smith machine hip raise", " abdominals", 0),
            Excercise("smith machine incline bench press", " chest", 0),
            Excercise("smith machine leg press", " quadriceps", 0),
            Excercise("smith machine one-arm upright row", " shoulders", 0),
            Excercise("smith machine overhead shoulder press", " shoulders", 0),
            Excercise("smith machine pistol squat", " quadriceps", 0),
            Excercise("smith machine reverse calf raises", " calves", 0),
            Excercise("smith machine shrug", " traps", 0),
            Excercise("smith machine squat", " quadriceps", 0),
            Excercise("smith machine stiff-legged deadlift", " hamstrings", 0),
            Excercise("smith machine upright row", " traps", 0),
            Excercise("smith single-leg split squat", " quadriceps", 0),
            Excercise("snatch", " quadriceps", 0),
            Excercise("snatch balance", " quadriceps", 0),
            Excercise("snatch deadlift", " hamstrings", 0),
            Excercise("snatch from blocks", " quadriceps", 0),
            Excercise("snatch pull", " hamstrings", 0),
            Excercise("snatch shrug", " traps", 0),
            Excercise("speed band overhead triceps", " triceps", 0),
            Excercise("speed band pushdown", " triceps", 0),
            Excercise("speed box squat", " quadriceps", 0),
            Excercise("speed squats", " quadriceps", 0),
            Excercise("spell caster", " abdominals", 0),
            Excercise("spider crawl", " abdominals", 0),
            Excercise("spider curl", " biceps", 0),
            Excercise("spinal stretch", " middle back", 0),
            Excercise("split clean", " quadriceps", 0),
            Excercise("split jerk", " quadriceps", 0),
            Excercise("split jump", " quadriceps", 0),
            Excercise("split snatch", " hamstrings", 0),
            Excercise("split squat with dumbbells", " quadriceps", 0),
            Excercise("split squats", " hamstrings", 0),
            Excercise("squat jerk", " quadriceps", 0),
            Excercise("squat with bands", " quadriceps", 0),
            Excercise("squat with chains", " quadriceps", 0),
            Excercise("squat with plate movers", " quadriceps", 0),
            Excercise("squats - with bands", " quadriceps", 0),
            Excercise("stairmaster", " quadriceps", 0),
            Excercise("standing alternating dumbbell press", " shoulders", 0),
            Excercise("standing barbell calf raise", " calves", 0),
            Excercise("standing barbell press behind neck", " shoulders", 0),
            Excercise("standing bent-over one-arm dumbbell triceps extension", " triceps", 0),
            Excercise("standing bent-over two-arm dumbbell triceps extension", " triceps", 0),
            Excercise("standing biceps cable curl", " biceps", 0),
            Excercise("standing biceps stretch", " biceps", 0),
            Excercise("standing bradford press", " shoulders", 0),
            Excercise("standing cable chest press", " chest", 0),
            Excercise("standing cable lift", " abdominals", 0),
            Excercise("standing cable wood chop", " abdominals", 0),
            Excercise("standing calf raises", " calves", 0),
            Excercise("standing concentration curl", " biceps", 0),
            Excercise("standing dumbbell calf raise", " calves", 0),
            Excercise("standing dumbbell press", " shoulders", 0),
            Excercise("standing dumbbell reverse curl", " biceps", 0),
            Excercise("standing dumbbell straight-arm front delt raise above head", " shoulders", 0),
            Excercise("standing dumbbell triceps extension", " triceps", 0),
            Excercise("standing dumbbell upright row", " traps", 0),
            Excercise("standing elevated quad stretch", " quadriceps", 0),
            Excercise("standing front barbell raise over head", " shoulders", 0),
            Excercise("standing gastrocnemius calf stretch", " calves", 0),
            Excercise("standing hamstring and calf stretch", " hamstrings", 0),
            Excercise("standing hip circles", " abductors", 0),
            Excercise("standing hip flexors", " quadriceps", 0),
            Excercise("standing inner-biceps curl", " biceps", 0),
            Excercise("standing lateral stretch", " abdominals", 0),
            Excercise("standing leg curl", " hamstrings", 0),
            Excercise("standing long jump", " quadriceps", 0),
            Excercise("standing low-pulley deltoid raise", " shoulders", 0),
            Excercise("standing low-pulley one-arm triceps extension", " triceps", 0),
            Excercise("standing military press", " shoulders", 0),
            Excercise("standing olympic plate hand squeeze", " forearms", 0),
            Excercise("standing one-arm cable curl", " biceps", 0),
            Excercise("standing one-arm dumbbell curl over incline bench", " biceps", 0),
            Excercise("standing one-arm dumbbell triceps extension", " triceps", 0),
            Excercise("standing overhead barbell triceps extension", " triceps", 0),
            Excercise("standing palm-in one-arm dumbbell press", " shoulders", 0),
            Excercise("standing palms-in dumbbell press", " shoulders", 0),
            Excercise("standing palms-up barbell behind the back wrist curl", " forearms", 0),
            Excercise("standing pelvic tilt", " lower back", 0),
            Excercise("standing rope crunch", " abdominals", 0),
            Excercise("standing soleus and achilles stretch", " calves", 0),
            Excercise("standing toe touches", " hamstrings", 0),
            Excercise("standing towel triceps extension", " triceps", 0),
            Excercise("standing two-arm overhead throw", " shoulders", 0),
            Excercise("star jump", " quadriceps", 0),
            Excercise("step mill", " quadriceps", 0),
            Excercise("step-up with knee raise", " glutes", 0),
            Excercise("stiff leg barbell good morning", " lower back", 0),
            Excercise("stiff-legged barbell deadlift", " hamstrings", 0),
            Excercise("stiff-legged dumbbell deadlift", " hamstrings", 0),
            Excercise("stomach vacuum", " abdominals", 0),
            Excercise("straight bar bench mid rows", " middle back", 0),
            Excercise("straight raises on incline bench", " shoulders", 0),
            Excercise("straight-arm dumbbell pullover", " chest", 0),
            Excercise("straight-arm pulldown", " lats", 0),
            Excercise("stride jump crossover", " quadriceps", 0),
            Excercise("sumo deadlift", " hamstrings", 0),
            Excercise("sumo deadlift with bands", " hamstrings", 0),
            Excercise("sumo deadlift with chains", " hamstrings", 0),
            Excercise("superman", " lower back", 0),
            Excercise("supine chest throw", " triceps", 0),
            Excercise("supine one-arm overhead throw", " abdominals", 0),
            Excercise("supine two-arm overhead throw", " abdominals", 0),
            Excercise("suspended push-up", " chest", 0),
            Excercise("suspended reverse crunch", " abdominals", 0),
            Excercise("suspended row", " middle back", 0),
            Excercise("suspended split squat", " quadriceps", 0),
            Excercise("t-bar row with handle", " middle back", 0),
            Excercise("tate press", " triceps", 0),
            Excercise("the straddle", " hamstrings", 0),
            Excercise("thigh abductor", " abductors", 0),
            Excercise("thigh adductor", " adductors", 0),
            Excercise("tire flip", " quadriceps", 0),
            Excercise("toe touchers", " abdominals", 0),
            Excercise("torso rotation", " abdominals", 0),
            Excercise("trail running/walking", " quadriceps", 0),
            Excercise("trap bar deadlift", " quadriceps", 0),
            Excercise("tricep dumbbell kickback", " triceps", 0),
            Excercise("tricep side stretch", " triceps", 0),
            Excercise("triceps overhead extension with rope", " triceps", 0),
            Excercise("triceps pushdown", " triceps", 0),
            Excercise("triceps pushdown - rope attachment", " triceps", 0),
            Excercise("triceps pushdown - v-bar attachment", " triceps", 0),
            Excercise("triceps stretch", " triceps", 0),
            Excercise("tuck crunch", " abdominals", 0),
            Excercise("two-arm dumbbell preacher curl", " biceps", 0),
            Excercise("two-arm kettlebell clean", " shoulders", 0),
            Excercise("two-arm kettlebell jerk", " shoulders", 0),
            Excercise("two-arm kettlebell military press", " shoulders", 0),
            Excercise("two-arm kettlebell row", " middle back", 0),
            Excercise("underhand cable pulldowns", " lats", 0),
            Excercise("upper back stretch", " middle back", 0),
            Excercise("upper back-leg grab", " hamstrings", 0),
            Excercise("upright barbell row", " shoulders", 0),
            Excercise("upright cable row", " traps", 0),
            Excercise("upright row - with bands", " traps", 0),
            Excercise("upward stretch", " shoulders", 0),
            Excercise("v-bar pulldown", " lats", 0),
            Excercise("v-bar pullup", " lats", 0),
            Excercise("vertical swing", " hamstrings", 0),
            Excercise("walking", " treadmill", 0),
            Excercise("weighted ball hyperextension", " lower back", 0),
            Excercise("weighted ball side bend", " abdominals", 0),
            Excercise("weighted bench dip", " triceps", 0),
            Excercise("weighted crunches", " abdominals", 0),
            Excercise("weighted jump squat", " quadriceps", 0),
            Excercise("weighted pull ups", " lats", 0),
            Excercise("weighted sissy squat", " quadriceps", 0),
            Excercise("weighted sit-ups - with bands", " abdominals", 0),
            Excercise("weighted squat", " quadriceps", 0),
            Excercise("wide stance barbell squat", " quadriceps", 0),
            Excercise("wide stance stiff legs", " hamstrings", 0),
            Excercise("wide-grip barbell bench press", " chest", 0),
            Excercise("wide-grip decline barbell bench press", " chest", 0),
            Excercise("wide-grip decline barbell pullover", " chest", 0),
            Excercise("wide-grip lat pulldown", " lats", 0),
            Excercise("wide-grip pulldown behind the neck", " lats", 0),
            Excercise("wide-grip rear pull-up", " lats", 0),
            Excercise("wide-grip standing barbell curl", " biceps", 0),
            Excercise("wind sprints", " abdominals", 0),
            Excercise("windmills", " abductors", 0),
            Excercise("world's greatest stretch", " hamstrings", 0),
            Excercise("wrist circles", " forearms", 0),
            Excercise("wrist roller", " forearms", 0),
            Excercise("wrist rotations with straight bar", " forearms", 0),
            Excercise("yoke walk", " quadriceps", 0),
            Excercise("zercher squats", " quadriceps", 0),
            Excercise("zottman curl", " biceps", 0),
            Excercise("zottman preacher curl", " biceps", 0)))*/