package com.example.fitnessapp.exercises

import android.os.Bundle
import android.text.Editable
import android.text.TextWatcher
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import androidx.fragment.app.FragmentManager
import androidx.fragment.app.FragmentTransaction
import androidx.recyclerview.widget.DividerItemDecoration
import androidx.recyclerview.widget.LinearLayoutManager
import com.example.fitnessapp.MainActivity
import com.example.fitnessapp.R
import com.example.fitnessapp.databinding.FragmentExercisesBinding


class ExercisesFragment : Fragment(), ExerciseAdapter.OnItemClickListener {

    private lateinit var binding: FragmentExercisesBinding
    private lateinit var exerciseDao: ExerciseDao
    private lateinit var parentActivity: MainActivity

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        binding = FragmentExercisesBinding.inflate(layoutInflater)
        parentActivity = activity as MainActivity
        exerciseDao = parentActivity.db.exerciseDao()                                                                                                               //
        val exercises: MutableList<Exercise> = exerciseDao.getAll()                                                                                 // gets all database items and puts it in a list
        binding.rvwExercises.adapter = ExerciseAdapter(exercises,this)                                                // adds the exercises list in the recyclerview
        binding.rvwExercises.layoutManager = LinearLayoutManager(context)                                        // chooses what type of layout
        binding.rvwExercises.addItemDecoration(DividerItemDecoration(context, DividerItemDecoration.VERTICAL))   // this puts a line between every item

        binding.filter.addTextChangedListener(object : TextWatcher {                                //this is used to check the typed word which than filters the recyclerview to show to exercises that have a matching name or muscle group
            override fun beforeTextChanged(s: CharSequence, start: Int, count: Int, after: Int) {}
            override fun onTextChanged(s: CharSequence, start: Int, before: Int, count: Int) {}
            override fun afterTextChanged(s: Editable) {
                val filteredList: ArrayList<Exercise> = ArrayList()                           // local arraylist where the matches item are stored
                for (item in exercises) {                                                     // for loop checks for match with every item
                    if (item.name.lowercase().contains(s.toString().lowercase())) {           // name match check
                        filteredList.add(item)                                                //
                    }                                                                         //
                    else if (item.muscleGroup.lowercase().contains(s.toString().lowercase())) {    // muscle group match check
                        filteredList.add(item)                                                //
                    }                                                                         //
                }                                                                             //
                binding.rvwExercises.adapter = ExerciseAdapter(filteredList,this@ExercisesFragment)                  // redraws the recyclerview
                binding.rvwExercises.layoutManager = LinearLayoutManager(context)             //
            }                                                                                 //
        })                                                                                    //

        return binding.root
    }
    override fun onClick(exercise: Exercise){
        val fragment: Fragment = ExercisesDetailsFragment(exercise)
        val fragmentManager: FragmentManager = requireActivity().supportFragmentManager
        val fragmentTransaction: FragmentTransaction = fragmentManager.beginTransaction()
        val containerId = R.id.fragment_container
        fragmentTransaction.replace(containerId, fragment)
        fragmentTransaction.addToBackStack(null)
        fragmentTransaction.commit()
    }
}






/*
exerciseDao.insert(listOf(Exercise("ab crunch machine", " abdominals", 0),
            Exercise("ab roller", " abdominals", 0),
            Exercise("adductor", " adductors", 0),
            Exercise("adductor/groin", " adductors", 0),
            Exercise("advanced kettlebell windmill", " abdominals", 0),
            Exercise("air bike", " abdominals", 0),
            Exercise("all fours quad stretch", " quadriceps", 0),
            Exercise("alternate hammer curl", " biceps", 0),
            Exercise("alternate heel touchers", " abdominals", 0),
            Exercise("alternate incline dumbbell curl", " biceps", 0),
            Exercise("alternate leg diagonal bound", " quadriceps", 0),
            Exercise("alternating cable shoulder press", " shoulders", 0),
            Exercise("alternating deltoid raise", " shoulders", 0),
            Exercise("alternating floor press", " chest", 0),
            Exercise("alternating hang clean", " hamstrings", 0),
            Exercise("alternating kettlebell press", " shoulders", 0),
            Exercise("alternating kettlebell row", " middle back", 0),
            Exercise("alternating renegade row", " middle back", 0),
            Exercise("ankle circles", " calves", 0),
            Exercise("ankle on the knee", " glutes", 0),
            Exercise("anterior tibialis-smr", " calves", 0),
            Exercise("anti-gravity press", " shoulders", 0),
            Exercise("arm circles", " shoulders", 0),
            Exercise("arnold dumbbell press", " shoulders", 0),
            Exercise("around the worlds", " chest", 0),
            Exercise("atlas stone trainer", " lower back", 0),
            Exercise("atlas stones", " lower back", 0),
            Exercise("axle deadlift", " lower back", 0),
            Exercise("ab crunch machine", " abdominals", 0),
            Exercise("ab roller", " abdominals", 0),
            Exercise("adductor", " adductors", 0),
            Exercise("adductor/groin", " adductors", 0),
            Exercise("advanced kettlebell windmill", " abdominals", 0),
            Exercise("air bike", " abdominals", 0),
            Exercise("all fours quad stretch", " quadriceps", 0),
            Exercise("alternate hammer curl", " biceps", 0),
            Exercise("alternate heel touchers", " abdominals", 0),
            Exercise("alternate incline dumbbell curl", " biceps", 0),
            Exercise("alternate leg diagonal bound", " quadriceps", 0),
            Exercise("alternating cable shoulder press", " shoulders", 0),
            Exercise("alternating deltoid raise", " shoulders", 0),
            Exercise("alternating floor press", " chest", 0),
            Exercise("alternating hang clean", " hamstrings", 0),
            Exercise("alternating kettlebell press", " shoulders", 0),
            Exercise("alternating kettlebell row", " middle back", 0),
            Exercise("alternating renegade row", " middle back", 0),
            Exercise("ankle circles", " calves", 0),
            Exercise("ankle on the knee", " glutes", 0),
            Exercise("anterior tibialis-smr", " calves", 0),
            Exercise("anti-gravity press", " shoulders", 0),
            Exercise("arm circles", " shoulders", 0),
            Exercise("arnold dumbbell press", " shoulders", 0),
            Exercise("around the worlds", " chest", 0),
            Exercise("atlas stone trainer", " lower back", 0),
            Exercise("atlas stones", " lower back", 0),
            Exercise("axle deadlift", " lower back", 0),
            Exercise("back flyes - with bands", " shoulders", 0),
            Exercise("backward drag", " quadriceps", 0),
            Exercise("backward medicine ball throw", " shoulders", 0),
            Exercise("balance board", " calves", 0),
            Exercise("ball leg curl", " hamstrings", 0),
            Exercise("band assisted pull-up", " lats", 0),
            Exercise("band good morning", " hamstrings", 0),
            Exercise("band good morning (pull through)", " hamstrings", 0),
            Exercise("band hip adductions", " adductors", 0),
            Exercise("band pull apart", " shoulders", 0),
            Exercise("band skull crusher", " triceps", 0),
            Exercise("barbell ab rollout", " abdominals", 0),
            Exercise("barbell ab rollout - on knees", " abdominals", 0),
            Exercise("barbell bench press - medium grip", " chest", 0),
            Exercise("barbell curl", " biceps", 0),
            Exercise("barbell curls lying against an incline", " biceps", 0),
            Exercise("barbell deadlift", " lower back", 0),
            Exercise("barbell full squat", " quadriceps", 0),
            Exercise("barbell glute bridge", " glutes", 0),
            Exercise("barbell guillotine bench press", " chest", 0),
            Exercise("barbell hack squat", " quadriceps", 0),
            Exercise("barbell hip thrust", " glutes", 0),
            Exercise("barbell incline bench press - medium grip", " chest", 0),
            Exercise("barbell incline shoulder raise", " shoulders", 0),
            Exercise("barbell lunge", " quadriceps", 0),
            Exercise("barbell rear delt row", " shoulders", 0),
            Exercise("barbell rollout from bench", " abdominals", 0),
            Exercise("barbell seated calf raise", " calves", 0),
            Exercise("barbell shoulder press", " shoulders", 0),
            Exercise("barbell shrug", " traps", 0),
            Exercise("barbell shrug behind the back", " traps", 0),
            Exercise("barbell side bend", " abdominals", 0),
            Exercise("barbell side split squat", " quadriceps", 0),
            Exercise("barbell squat", " quadriceps", 0),
            Exercise("barbell squat to a bench", " quadriceps", 0),
            Exercise("barbell step ups", " quadriceps", 0),
            Exercise("barbell walking lunge", " quadriceps", 0),
            Exercise("battling ropes", " shoulders", 0),
            Exercise("bear crawl sled drags", " quadriceps", 0),
            Exercise("behind head chest stretch", " chest", 0),
            Exercise("bench dips", " triceps", 0),
            Exercise("bench jump", " quadriceps", 0),
            Exercise("bench press - powerlifting", " triceps", 0),
            Exercise("bench press - with bands", " chest", 0),
            Exercise("bench press with chains", " triceps", 0),
            Exercise("bench sprint", " quadriceps", 0),
            Exercise("bent over barbell row", " middle back", 0),
            Exercise("bent over dumbbell rear delt raise with head on bench", " shoulders", 0),
            Exercise("bent over low-pulley side lateral", " shoulders", 0),
            Exercise("bent over one-arm long bar row", " middle back", 0),
            Exercise("bent over two-arm long bar row", " middle back", 0),
            Exercise("bent over two-dumbbell row", " middle back", 0),
            Exercise("bent over two-dumbbell row with palms in", " middle back", 0),
            Exercise("bent press", " abdominals", 0),
            Exercise("bent-arm barbell pullover", " lats", 0),
            Exercise("bent-arm dumbbell pullover", " chest", 0),
            Exercise("bent-knee hip raise", " abdominals", 0),
            Exercise("bicycling", " quadriceps", 0),
            Exercise("bicycling", " stationary", 0),
            Exercise("board press", " triceps", 0),
            Exercise("body tricep press", " triceps", 0),
            Exercise("body-up", " triceps", 0),
            Exercise("bodyweight flyes", " chest", 0),
            Exercise("bodyweight mid row", " middle back", 0),
            Exercise("bodyweight squat", " quadriceps", 0),
            Exercise("bodyweight walking lunge", " quadriceps", 0),
            Exercise("bosu ball cable crunch with side bends", " abdominals", 0),
            Exercise("bottoms up", " abdominals", 0),
            Exercise("bottoms-up clean from the hang position", " forearms", 0),
            Exercise("box jump (multiple response)", " hamstrings", 0),
            Exercise("box skip", " hamstrings", 0),
            Exercise("box squat", " quadriceps", 0),
            Exercise("box squat with bands", " quadriceps", 0),
            Exercise("box squat with chains", " quadriceps", 0),
            Exercise("brachialis-smr", " biceps", 0),
            Exercise("bradford/rocky presses", " shoulders", 0),
            Exercise("butt lift (bridge)", " glutes", 0),
            Exercise("butt-ups", " abdominals", 0),
            Exercise("butterfly", " chest", 0),
            Exercise("cable chest press", " chest", 0),
            Exercise("cable crossover", " chest", 0),
            Exercise("cable crunch", " abdominals", 0),
            Exercise("cable deadlifts", " quadriceps", 0),
            Exercise("cable hammer curls - rope attachment", " biceps", 0),
            Exercise("cable hip adduction", " quadriceps", 0),
            Exercise("cable incline pushdown", " lats", 0),
            Exercise("cable incline triceps extension", " triceps", 0),
            Exercise("cable internal rotation", " shoulders", 0),
            Exercise("cable iron cross", " chest", 0),
            Exercise("cable judo flip", " abdominals", 0),
            Exercise("cable lying triceps extension", " triceps", 0),
            Exercise("cable one arm tricep extension", " triceps", 0),
            Exercise("cable preacher curl", " biceps", 0),
            Exercise("cable rear delt fly", " shoulders", 0),
            Exercise("cable reverse crunch", " abdominals", 0),
            Exercise("cable rope overhead triceps extension", " triceps", 0),
            Exercise("cable rope rear-delt rows", " shoulders", 0),
            Exercise("cable russian twists", " abdominals", 0),
            Exercise("cable seated crunch", " abdominals", 0),
            Exercise("cable seated lateral raise", " shoulders", 0),
            Exercise("cable shoulder press", " shoulders", 0),
            Exercise("cable shrugs", " traps", 0),
            Exercise("cable tuck reverse crunch", " abdominals", 0),
            Exercise("cable wrist curl", " forearms", 0),
            Exercise("calf press", " calves", 0),
            Exercise("calf press on the leg press machine", " calves", 0),
            Exercise("calf raise on a dumbbell", " calves", 0),
            Exercise("calf raises - with bands", " calves", 0),
            Exercise("calf stretch elbows against wall", " calves", 0),
            Exercise("calf stretch hands against wall", " calves", 0),
            Exercise("calf-machine shoulder shrug", " traps", 0),
            Exercise("calves-smr", " calves", 0),
            Exercise("car deadlift", " quadriceps", 0),
            Exercise("car drivers", " shoulders", 0),
            Exercise("carioca quick step", " adductors", 0),
            Exercise("cat stretch", " lower back", 0),
            Exercise("catch and overhead throw", " lats", 0),
            Exercise("chain handle extension", " triceps", 0),
            Exercise("chain press", " chest", 0),
            Exercise("chair leg extended stretch", " hamstrings", 0),
            Exercise("chair lower back stretch", " lats", 0),
            Exercise("chair squat", " quadriceps", 0),
            Exercise("chair upper body stretch", " shoulders", 0),
            Exercise("chest and front of shoulder stretch", " chest", 0),
            Exercise("chest push (multiple response)", " chest", 0),
            Exercise("chest push (single response)", " chest", 0),
            Exercise("chest push from 3 point stance", " chest", 0),
            Exercise("chest push with run release", " chest", 0),
            Exercise("chest stretch on stability ball", " chest", 0),
            Exercise("child's pose", " lower back", 0),
            Exercise("chin to chest stretch", " neck", 0),
            Exercise("chin-up", " lats", 0),
            Exercise("circus bell", " shoulders", 0),
            Exercise("clean", " hamstrings", 0),
            Exercise("clean and jerk", " shoulders", 0),
            Exercise("clean and press", " shoulders", 0),
            Exercise("clean deadlift", " hamstrings", 0),
            Exercise("clean from blocks", " quadriceps", 0),
            Exercise("clean pull", " quadriceps", 0),
            Exercise("clean shrug", " traps", 0),
            Exercise("clock push-up", " chest", 0),
            Exercise("close-grip barbell bench press", " triceps", 0),
            Exercise("close-grip dumbbell press", " triceps", 0),
            Exercise("close-grip ez bar curl", " biceps", 0),
            Exercise("close-grip ez-bar curl with band", " biceps", 0),
            Exercise("close-grip ez-bar press", " triceps", 0),
            Exercise("close-grip front lat pulldown", " lats", 0),
            Exercise("close-grip push-up off of a dumbbell", " triceps", 0),
            Exercise("close-grip standing barbell curl", " biceps", 0),
            Exercise("cocoons", " abdominals", 0),
            Exercise("conan's wheel", " quadriceps", 0),
            Exercise("concentration curls", " biceps", 0),
            Exercise("cross body hammer curl", " biceps", 0),
            Exercise("cross over - with bands", " chest", 0),
            Exercise("cross-body crunch", " abdominals", 0),
            Exercise("crossover reverse lunge", " lower back", 0),
            Exercise("crucifix", " shoulders", 0),
            Exercise("crunch - hands overhead", " abdominals", 0),
            Exercise("crunch - legs on exercise ball", " abdominals", 0),
            Exercise("crunches", " abdominals", 0),
            Exercise("cuban press", " shoulders", 0),
            Exercise("dancer's stretch", " lower back", 0),
            Exercise("deadlift with bands", " lower back", 0),
            Exercise("deadlift with chains", " lower back", 0),
            Exercise("decline barbell bench press", " chest", 0),
            Exercise("decline close-grip bench to skull crusher", " triceps", 0),
            Exercise("decline crunch", " abdominals", 0),
            Exercise("decline dumbbell bench press", " chest", 0),
            Exercise("decline dumbbell flyes", " chest", 0),
            Exercise("decline dumbbell triceps extension", " triceps", 0),
            Exercise("decline ez bar triceps extension", " triceps", 0),
            Exercise("decline oblique crunch", " abdominals", 0),
            Exercise("decline push-up", " chest", 0),
            Exercise("decline reverse crunch", " abdominals", 0),
            Exercise("decline smith press", " chest", 0),
            Exercise("deficit deadlift", " lower back", 0),
            Exercise("depth jump leap", " quadriceps", 0),
            Exercise("dip machine", " triceps", 0),
            Exercise("dips - chest version", " chest", 0),
            Exercise("dips - triceps version", " triceps", 0),
            Exercise("donkey calf raises", " calves", 0),
            Exercise("double kettlebell alternating hang clean", " hamstrings", 0),
            Exercise("double kettlebell jerk", " shoulders", 0),
            Exercise("double kettlebell push press", " shoulders", 0),
            Exercise("double kettlebell snatch", " shoulders", 0),
            Exercise("double kettlebell windmill", " abdominals", 0),
            Exercise("double leg butt kick", " quadriceps", 0),
            Exercise("downward facing balance", " glutes", 0),
            Exercise("drag curl", " biceps", 0),
            Exercise("drop push", " chest", 0),
            Exercise("dumbbell alternate bicep curl", " biceps", 0),
            Exercise("dumbbell bench press", " chest", 0),
            Exercise("dumbbell bench press with neutral grip", " chest", 0),
            Exercise("dumbbell bicep curl", " biceps", 0),
            Exercise("dumbbell clean", " hamstrings", 0),
            Exercise("dumbbell floor press", " triceps", 0),
            Exercise("dumbbell flyes", " chest", 0),
            Exercise("dumbbell incline row", " middle back", 0),
            Exercise("dumbbell incline shoulder raise", " shoulders", 0),
            Exercise("dumbbell lunges", " quadriceps", 0),
            Exercise("dumbbell lying one-arm rear lateral raise", " shoulders", 0),
            Exercise("dumbbell lying pronation", " forearms", 0),
            Exercise("dumbbell lying rear lateral raise", " shoulders", 0),
            Exercise("dumbbell lying supination", " forearms", 0),
            Exercise("dumbbell one-arm shoulder press", " shoulders", 0),
            Exercise("dumbbell one-arm triceps extension", " triceps", 0),
            Exercise("dumbbell one-arm upright row", " shoulders", 0),
            Exercise("dumbbell prone incline curl", " biceps", 0),
            Exercise("dumbbell raise", " shoulders", 0),
            Exercise("dumbbell rear lunge", " quadriceps", 0),
            Exercise("dumbbell scaption", " shoulders", 0),
            Exercise("dumbbell seated box jump", " quadriceps", 0),
            Exercise("dumbbell seated one-leg calf raise", " calves", 0),
            Exercise("dumbbell shoulder press", " shoulders", 0),
            Exercise("dumbbell shrug", " traps", 0),
            Exercise("dumbbell side bend", " abdominals", 0),
            Exercise("dumbbell squat", " quadriceps", 0),
            Exercise("dumbbell squat to a bench", " quadriceps", 0),
            Exercise("dumbbell step ups", " quadriceps", 0),
            Exercise("dumbbell tricep extension -pronated grip", " triceps", 0),
            Exercise("dynamic back stretch", " lats", 0),
            Exercise("dynamic chest stretch", " chest", 0),
            Exercise("elbow circles", " shoulders", 0),
            Exercise("elbow to knee", " abdominals", 0),
            Exercise("elbows back", " chest", 0),
            Exercise("elevated back lunge", " quadriceps", 0),
            Exercise("elevated cable rows", " lats", 0),
            Exercise("elliptical trainer", " quadriceps", 0),
            Exercise("exercise ball crunch", " abdominals", 0),
            Exercise("exercise ball pull-in", " abdominals", 0),
            Exercise("extended range one-arm kettlebell floor press", " chest", 0),
            Exercise("external rotation", " shoulders", 0),
            Exercise("external rotation with band", " shoulders", 0),
            Exercise("external rotation with cable", " shoulders", 0),
            Exercise("ez-bar curl", " biceps", 0),
            Exercise("ez-bar skullcrusher", " triceps", 0),
            Exercise("face pull", " shoulders", 0),
            Exercise("farmer's walk", " forearms", 0),
            Exercise("fast skipping", " quadriceps", 0),
            Exercise("finger curls", " forearms", 0),
            Exercise("flat bench cable flyes", " chest", 0),
            Exercise("flat bench leg pull-in", " abdominals", 0),
            Exercise("flat bench lying leg raise", " abdominals", 0),
            Exercise("flexor incline dumbbell curls", " biceps", 0),
            Exercise("floor glute-ham raise", " hamstrings", 0),
            Exercise("floor press", " triceps", 0),
            Exercise("floor press with chains", " triceps", 0),
            Exercise("flutter kicks", " glutes", 0),
            Exercise("foot-smr", " calves", 0),
            Exercise("forward drag with press", " chest", 0),
            Exercise("frankenstein squat", " quadriceps", 0),
            Exercise("freehand jump squat", " quadriceps", 0),
            Exercise("frog hops", " quadriceps", 0),
            Exercise("frog sit-ups", " abdominals", 0),
            Exercise("front barbell squat", " quadriceps", 0),
            Exercise("front barbell squat to a bench", " quadriceps", 0),
            Exercise("front box jump", " hamstrings", 0),
            Exercise("front cable raise", " shoulders", 0),
            Exercise("front cone hops (or hurdle hops)", " quadriceps", 0),
            Exercise("front dumbbell raise", " shoulders", 0),
            Exercise("front incline dumbbell raise", " shoulders", 0),
            Exercise("front leg raises", " hamstrings", 0),
            Exercise("front plate raise", " shoulders", 0),
            Exercise("front raise and pullover", " chest", 0),
            Exercise("front squat (clean grip)", " quadriceps", 0),
            Exercise("front squats with two kettlebells", " quadriceps", 0),
            Exercise("front two-dumbbell raise", " shoulders", 0),
            Exercise("full range-of-motion lat pulldown", " lats", 0),
            Exercise("gironda sternum chins", " lats", 0),
            Exercise("glute ham raise", " hamstrings", 0),
            Exercise("glute kickback", " glutes", 0),
            Exercise("goblet squat", " quadriceps", 0),
            Exercise("good morning", " hamstrings", 0),
            Exercise("good morning off pins", " hamstrings", 0),
            Exercise("gorilla chin/crunch", " abdominals", 0),
            Exercise("groin and back stretch", " adductors", 0),
            Exercise("groiners", " adductors", 0),
            Exercise("hack squat", " quadriceps", 0),
            Exercise("hammer curls", " biceps", 0),
            Exercise("hammer grip incline db bench press", " chest", 0),
            Exercise("hamstring stretch", " hamstrings", 0),
            Exercise("hamstring-smr", " hamstrings", 0),
            Exercise("handstand push-ups", " shoulders", 0),
            Exercise("hang clean", " quadriceps", 0),
            Exercise("hang clean - below the knees", " quadriceps", 0),
            Exercise("hang snatch", " hamstrings", 0),
            Exercise("hang snatch - below knees", " hamstrings", 0),
            Exercise("hanging bar good morning", " hamstrings", 0),
            Exercise("hanging leg raise", " abdominals", 0),
            Exercise("hanging pike", " abdominals", 0),
            Exercise("heaving snatch balance", " quadriceps", 0),
            Exercise("heavy bag thrust", " chest", 0),
            Exercise("high cable curls", " biceps", 0),
            Exercise("hip circles (prone)", " abductors", 0),
            Exercise("hip crossover", "", 0),
            Exercise("hip extension with bands", " glutes", 0),
            Exercise("hip flexion with band", " quadriceps", 0),
            Exercise("hip lift with band", " glutes", 0),
            Exercise("hug a ball", " lower back", 0),
            Exercise("hug knees to chest", " lower back", 0),
            Exercise("hurdle hops", " hamstrings", 0),
            Exercise("hyperextensions (back extensions)", " lower back", 0),
            Exercise("hyperextensions with no hyperextension bench", " lower back", 0),
            Exercise("iliotibial tract-smr", " abductors", 0),
            Exercise("incline barbell triceps extension", " triceps", 0),
            Exercise("incline bench pull", " middle back", 0),
            Exercise("incline cable chest press", " chest", 0),
            Exercise("incline cable flye", " chest", 0),
            Exercise("incline dumbbell bench with palms facing in", " chest", 0),
            Exercise("incline dumbbell curl", " biceps", 0),
            Exercise("incline dumbbell flyes", " chest", 0),
            Exercise("incline dumbbell flyes - with a twist", " chest", 0),
            Exercise("incline dumbbell press", " chest", 0),
            Exercise("incline hammer curls", " biceps", 0),
            Exercise("incline inner biceps curl", " biceps", 0),
            Exercise("incline push-up", " chest", 0),
            Exercise("incline push-up close-grip", " triceps", 0),
            Exercise("incline push-up depth jump", " chest", 0),
            Exercise("incline push-up medium", " chest", 0),
            Exercise("incline push-up reverse grip", " chest", 0),
            Exercise("incline push-up wide", " chest", 0),
            Exercise("intermediate groin stretch", " hamstrings", 0),
            Exercise("intermediate hip flexor and quad stretch", " quadriceps", 0),
            Exercise("internal rotation with band", " shoulders", 0),
            Exercise("inverted row", " middle back", 0),
            Exercise("inverted row with straps", " middle back", 0),
            Exercise("iron cross", " shoulders", 0),
            Exercise("iron crosses (stretch)", " quadriceps", 0),
            Exercise("isometric chest squeezes", " chest", 0),
            Exercise("isometric neck exercise - front and back", " neck", 0),
            Exercise("isometric neck exercise - sides", " neck", 0),
            Exercise("isometric wipers", " chest", 0),
            Exercise("it band and glute stretch", " abductors", 0),
            Exercise("jackknife sit-up", " abdominals", 0),
            Exercise("janda sit-up", " abdominals", 0),
            Exercise("jefferson squats", " quadriceps", 0),
            Exercise("jerk balance", " shoulders", 0),
            Exercise("jerk dip squat", " quadriceps", 0),
            Exercise("jm press", " triceps", 0),
            Exercise("jogging-treadmill", " quadriceps", 0),
            Exercise("keg load", " lower back", 0),
            Exercise("kettlebell arnold press", " shoulders", 0),
            Exercise("kettlebell dead clean", " hamstrings", 0),
            Exercise("kettlebell figure 8", " abdominals", 0),
            Exercise("kettlebell hang clean", " hamstrings", 0),
            Exercise("kettlebell one-legged deadlift", " hamstrings", 0),
            Exercise("kettlebell pass between the legs", " abdominals", 0),
            Exercise("kettlebell pirate ships", " shoulders", 0),
            Exercise("kettlebell pistol squat", " quadriceps", 0),
            Exercise("kettlebell seated press", " shoulders", 0),
            Exercise("kettlebell seesaw press", " shoulders", 0),
            Exercise("kettlebell sumo high pull", " traps", 0),
            Exercise("kettlebell thruster", " shoulders", 0),
            Exercise("kettlebell turkish get-up (lunge style)", " shoulders", 0),
            Exercise("kettlebell turkish get-up (squat style)", " shoulders", 0),
            Exercise("kettlebell windmill", " abdominals", 0),
            Exercise("kipping muscle up", " lats", 0),
            Exercise("knee across the body", " glutes", 0),
            Exercise("knee circles", " calves", 0),
            Exercise("knee tuck jump", " hamstrings", 0),
            Exercise("knee/hip raise on parallel bars", " abdominals", 0),
            Exercise("kneeling arm drill", " shoulders", 0),
            Exercise("kneeling cable crunch with alternating oblique twists", " abdominals", 0),
            Exercise("kneeling cable triceps extension", " triceps", 0),
            Exercise("kneeling forearm stretch", " forearms", 0),
            Exercise("kneeling high pulley row", " lats", 0),
            Exercise("kneeling hip flexor", " quadriceps", 0),
            Exercise("kneeling jump squat", " glutes", 0),
            Exercise("kneeling single-arm high pulley row", " lats", 0),
            Exercise("kneeling squat", " glutes", 0),
            Exercise("landmine 180's", " abdominals", 0),
            Exercise("landmine linear jammer", " shoulders", 0),
            Exercise("lateral bound", " adductors", 0),
            Exercise("lateral box jump", " adductors", 0),
            Exercise("lateral cone hops", " adductors", 0),
            Exercise("lateral raise - with bands", " shoulders", 0),
            Exercise("latissimus dorsi-smr", " lats", 0),
            Exercise("leg extensions", " quadriceps", 0),
            Exercise("leg lift", " glutes", 0),
            Exercise("leg press", " quadriceps", 0),
            Exercise("leg pull-in", " abdominals", 0),
            Exercise("leg-over floor press", " chest", 0),
            Exercise("leg-up hamstring stretch", " hamstrings", 0),
            Exercise("leverage chest press", " chest", 0),
            Exercise("leverage deadlift", " quadriceps", 0),
            Exercise("leverage decline chest press", " chest", 0),
            Exercise("leverage high row", " middle back", 0),
            Exercise("leverage incline chest press", " chest", 0),
            Exercise("leverage iso row", " lats", 0),
            Exercise("leverage shoulder press", " shoulders", 0),
            Exercise("leverage shrug", " traps", 0),
            Exercise("linear 3-part start technique", " hamstrings", 0),
            Exercise("linear acceleration wall drill", " hamstrings", 0),
            Exercise("linear depth jump", " quadriceps", 0),
            Exercise("log lift", " shoulders", 0),
            Exercise("london bridges", " lats", 0),
            Exercise("looking at ceiling", " quadriceps", 0),
            Exercise("low cable crossover", " chest", 0),
            Exercise("low cable triceps extension", " triceps", 0),
            Exercise("low pulley row to neck", " shoulders", 0),
            Exercise("lower back curl", " abdominals", 0),
            Exercise("lower back-smr", " lower back", 0),
            Exercise("lunge pass through", " hamstrings", 0),
            Exercise("lunge sprint", " quadriceps", 0),
            Exercise("lying bent leg groin", " adductors", 0),
            Exercise("lying cable curl", " biceps", 0),
            Exercise("lying cambered barbell row", " middle back", 0),
            Exercise("lying close-grip bar curl on high pulley", " biceps", 0),
            Exercise("lying close-grip barbell triceps extension behind the head", " triceps", 0),
            Exercise("lying close-grip barbell triceps press to chin", " triceps", 0),
            Exercise("lying crossover", " abductors", 0),
            Exercise("lying dumbbell tricep extension", " triceps", 0),
            Exercise("lying face down plate neck resistance", " neck", 0),
            Exercise("lying face up plate neck resistance", " neck", 0),
            Exercise("lying glute", " glutes", 0),
            Exercise("lying hamstring", " hamstrings", 0),
            Exercise("lying high bench barbell curl", " biceps", 0),
            Exercise("lying leg curls", " hamstrings", 0),
            Exercise("lying machine squat", " quadriceps", 0),
            Exercise("lying one-arm lateral raise", " shoulders", 0),
            Exercise("lying prone quadriceps", " quadriceps", 0),
            Exercise("lying rear delt raise", " shoulders", 0),
            Exercise("lying supine dumbbell curl", " biceps", 0),
            Exercise("lying t-bar row", " middle back", 0),
            Exercise("lying triceps press", " triceps", 0),
            Exercise("machine bench press", " chest", 0),
            Exercise("machine bicep curl", " biceps", 0),
            Exercise("machine preacher curls", " biceps", 0),
            Exercise("machine shoulder (military) press", " shoulders", 0),
            Exercise("machine triceps extension", " triceps", 0),
            Exercise("medicine ball chest pass", " chest", 0),
            Exercise("medicine ball full twist", " abdominals", 0),
            Exercise("medicine ball scoop throw", " shoulders", 0),
            Exercise("middle back shrug", " middle back", 0),
            Exercise("middle back stretch", " middle back", 0),
            Exercise("mixed grip chin", " middle back", 0),
            Exercise("monster walk", " abductors", 0),
            Exercise("mountain climbers", " quadriceps", 0),
            Exercise("moving claw series", " hamstrings", 0),
            Exercise("muscle snatch", " hamstrings", 0),
            Exercise("muscle up", " lats", 0),
            Exercise("narrow stance hack squats", " quadriceps", 0),
            Exercise("narrow stance leg press", " quadriceps", 0),
            Exercise("narrow stance squats", " quadriceps", 0),
            Exercise("natural glute ham raise", " hamstrings", 0),
            Exercise("neck press", " chest", 0),
            Exercise("neck-smr", " neck", 0),
            Exercise("oblique crunches", " abdominals", 0),
            Exercise("oblique crunches - on the floor", " abdominals", 0),
            Exercise("olympic squat", " quadriceps", 0),
            Exercise("on your side quad stretch", " quadriceps", 0),
            Exercise("on-your-back quad stretch", " quadriceps", 0),
            Exercise("one arm against wall", " lats", 0),
            Exercise("one arm chin-up", " middle back", 0),
            Exercise("one arm dumbbell bench press", " chest", 0),
            Exercise("one arm dumbbell preacher curl", " biceps", 0),
            Exercise("one arm floor press", " triceps", 0),
            Exercise("one arm lat pulldown", " lats", 0),
            Exercise("one arm pronated dumbbell triceps extension", " triceps", 0),
            Exercise("one arm supinated dumbbell triceps extension", " triceps", 0),
            Exercise("one half locust", " quadriceps", 0),
            Exercise("one handed hang", " lats", 0),
            Exercise("one knee to chest", " glutes", 0),
            Exercise("one leg barbell squat", " quadriceps", 0),
            Exercise("one-arm dumbbell row", " middle back", 0),
            Exercise("one-arm flat bench dumbbell flye", " chest", 0),
            Exercise("one-arm high-pulley cable side bends", " abdominals", 0),
            Exercise("one-arm incline lateral raise", " shoulders", 0),
            Exercise("one-arm kettlebell clean", " hamstrings", 0),
            Exercise("one-arm kettlebell clean and jerk", " shoulders", 0),
            Exercise("one-arm kettlebell floor press", " chest", 0),
            Exercise("one-arm kettlebell jerk", " shoulders", 0),
            Exercise("one-arm kettlebell military press to the side", " shoulders", 0),
            Exercise("one-arm kettlebell para press", " shoulders", 0),
            Exercise("one-arm kettlebell push press", " shoulders", 0),
            Exercise("one-arm kettlebell row", " middle back", 0),
            Exercise("one-arm kettlebell snatch", " shoulders", 0),
            Exercise("one-arm kettlebell split jerk", " shoulders", 0),
            Exercise("one-arm kettlebell split snatch", " shoulders", 0),
            Exercise("one-arm kettlebell swings", " hamstrings", 0),
            Exercise("one-arm long bar row", " middle back", 0),
            Exercise("one-arm medicine ball slam", " abdominals", 0),
            Exercise("one-arm open palm kettlebell clean", " hamstrings", 0),
            Exercise("one-arm overhead kettlebell squats", " quadriceps", 0),
            Exercise("one-arm side deadlift", " quadriceps", 0),
            Exercise("one-arm side laterals", " shoulders", 0),
            Exercise("one-legged cable kickback", " glutes", 0),
            Exercise("open palm kettlebell clean", " hamstrings", 0),
            Exercise("otis-up", " abdominals", 0),
            Exercise("overhead cable curl", " biceps", 0),
            Exercise("overhead lat", " lats", 0),
            Exercise("overhead slam", " lats", 0),
            Exercise("overhead squat", " quadriceps", 0),
            Exercise("overhead stretch", " abdominals", 0),
            Exercise("overhead triceps", " triceps", 0),
            Exercise("pallof press with rotation", " abdominals", 0),
            Exercise("palms-down dumbbell wrist curl over a bench", " forearms", 0),
            Exercise("palms-down wrist curl over a bench", " forearms", 0),
            Exercise("palms-up barbell wrist curl over a bench", " forearms", 0),
            Exercise("palms-up dumbbell wrist curl over a bench", " forearms", 0),
            Exercise("parallel bar dip", " triceps", 0),
            Exercise("pelvic tilt into bridge", " lower back", 0),
            Exercise("peroneals stretch", " calves", 0),
            Exercise("peroneals-smr", " calves", 0),
            Exercise("physioball hip bridge", " glutes", 0),
            Exercise("pin presses", " triceps", 0),
            Exercise("piriformis-smr", " glutes", 0),
            Exercise("plank", " abdominals", 0),
            Exercise("plank with twist", "", 0),
            Exercise("plate pinch", " forearms", 0),
            Exercise("plate twist", " abdominals", 0),
            Exercise("platform hamstring slides", " hamstrings", 0),
            Exercise("plie dumbbell squat", " quadriceps", 0),
            Exercise("plyo kettlebell pushups", " chest", 0),
            Exercise("plyo push-up", " chest", 0),
            Exercise("posterior tibialis stretch", " calves", 0),
            Exercise("power clean", " hamstrings", 0),
            Exercise("power clean from blocks", " hamstrings", 0),
            Exercise("power jerk", " quadriceps", 0),
            Exercise("power partials", " shoulders", 0),
            Exercise("power snatch", " hamstrings", 0),
            Exercise("power snatch from blocks", " quadriceps", 0),
            Exercise("power stairs", " hamstrings", 0),
            Exercise("preacher curl", " biceps", 0),
            Exercise("preacher hammer dumbbell curl", " biceps", 0),
            Exercise("press sit-up", " abdominals", 0),
            Exercise("prone manual hamstring", " hamstrings", 0),
            Exercise("prowler sprint", " hamstrings", 0),
            Exercise("pull through", " glutes", 0),
            Exercise("pullups", " lats", 0),
            Exercise("push press", " shoulders", 0),
            Exercise("push press - behind the neck", " shoulders", 0),
            Exercise("push up to side plank", " chest", 0),
            Exercise("push-up wide", " chest", 0),
            Exercise("push-ups - close triceps position", " triceps", 0),
            Exercise("push-ups with feet elevated", " chest", 0),
            Exercise("push-ups with feet on an exercise ball", " chest", 0),
            Exercise("pushups", " chest", 0),
            Exercise("pushups (close and wide hand positions)", " chest", 0),
            Exercise("pyramid", " lower back", 0),
            Exercise("quad stretch", " quadriceps", 0),
            Exercise("quadriceps-smr", " quadriceps", 0),
            Exercise("quick leap", " quadriceps", 0),
            Exercise("rack delivery", " shoulders", 0),
            Exercise("rack pull with bands", " lower back", 0),
            Exercise("rack pulls", " lower back", 0),
            Exercise("rear leg raises", " quadriceps", 0),
            Exercise("recumbent bike", " quadriceps", 0),
            Exercise("return push from stance", " shoulders", 0),
            Exercise("reverse band bench press", " triceps", 0),
            Exercise("reverse band box squat", " quadriceps", 0),
            Exercise("reverse band deadlift", " lower back", 0),
            Exercise("reverse band power squat", " quadriceps", 0),
            Exercise("reverse band sumo deadlift", " hamstrings", 0),
            Exercise("reverse barbell curl", " biceps", 0),
            Exercise("reverse barbell preacher curls", " biceps", 0),
            Exercise("reverse cable curl", " biceps", 0),
            Exercise("reverse crunch", " abdominals", 0),
            Exercise("reverse flyes", " shoulders", 0),
            Exercise("reverse flyes with external rotation", " shoulders", 0),
            Exercise("reverse grip bent-over rows", " middle back", 0),
            Exercise("reverse grip triceps pushdown", " triceps", 0),
            Exercise("reverse hyperextension", " hamstrings", 0),
            Exercise("reverse machine flyes", " shoulders", 0),
            Exercise("reverse plate curls", " biceps", 0),
            Exercise("reverse triceps bench press", " triceps", 0),
            Exercise("rhomboids-smr", " middle back", 0),
            Exercise("rickshaw carry", " forearms", 0),
            Exercise("rickshaw deadlift", " quadriceps", 0),
            Exercise("ring dips", " triceps", 0),
            Exercise("rocket jump", " quadriceps", 0),
            Exercise("rocking standing calf raise", " calves", 0),
            Exercise("rocky pull-ups/pulldowns", " lats", 0),
            Exercise("romanian deadlift", " hamstrings", 0),
            Exercise("romanian deadlift from deficit", " hamstrings", 0),
            Exercise("rope climb", " lats", 0),
            Exercise("rope crunch", " abdominals", 0),
            Exercise("rope jumping", " quadriceps", 0),
            Exercise("rope straight-arm pulldown", " lats", 0),
            Exercise("round the world shoulder stretch", " shoulders", 0),
            Exercise("rowing", " stationary", 0),
            Exercise("runner's stretch", " hamstrings", 0),
            Exercise("running", " treadmill", 0),
            Exercise("russian twist", " abdominals", 0),
            Exercise("sandbag load", " quadriceps", 0),
            Exercise("scapular pull-up", " traps", 0),
            Exercise("scissor kick", " abdominals", 0),
            Exercise("scissors jump", " quadriceps", 0),
            Exercise("seated band hamstring curl", " hamstrings", 0),
            Exercise("seated barbell military press", " shoulders", 0),
            Exercise("seated barbell twist", " abdominals", 0),
            Exercise("seated bent-over one-arm dumbbell triceps extension", " triceps", 0),
            Exercise("seated bent-over rear delt raise", " shoulders", 0),
            Exercise("seated bent-over two-arm dumbbell triceps extension", " triceps", 0),
            Exercise("seated biceps", " biceps", 0),
            Exercise("seated cable rows", " middle back", 0),
            Exercise("seated cable shoulder press", " shoulders", 0),
            Exercise("seated calf raise", " calves", 0),
            Exercise("seated calf stretch", " calves", 0),
            Exercise("seated close-grip concentration barbell curl", " biceps", 0),
            Exercise("seated dumbbell curl", " biceps", 0),
            Exercise("seated dumbbell inner biceps curl", " biceps", 0),
            Exercise("seated dumbbell palms-down wrist curl", " forearms", 0),
            Exercise("seated dumbbell palms-up wrist curl", " forearms", 0),
            Exercise("seated dumbbell press", " shoulders", 0),
            Exercise("seated flat bench leg pull-in", " abdominals", 0),
            Exercise("seated floor hamstring stretch", " hamstrings", 0),
            Exercise("seated front deltoid", " shoulders", 0),
            Exercise("seated glute", " glutes", 0),
            Exercise("seated good mornings", " lower back", 0),
            Exercise("seated hamstring", " hamstrings", 0),
            Exercise("seated hamstring and calf stretch", " hamstrings", 0),
            Exercise("seated head harness neck resistance", " neck", 0),
            Exercise("seated leg curl", " hamstrings", 0),
            Exercise("seated leg tucks", " abdominals", 0),
            Exercise("seated one-arm cable pulley rows", " middle back", 0),
            Exercise("seated one-arm dumbbell palms-down wrist curl", " forearms", 0),
            Exercise("seated one-arm dumbbell palms-up wrist curl", " forearms", 0),
            Exercise("seated overhead stretch", " abdominals", 0),
            Exercise("seated palm-up barbell wrist curl", " forearms", 0),
            Exercise("seated palms-down barbell wrist curl", " forearms", 0),
            Exercise("seated side lateral raise", " shoulders", 0),
            Exercise("seated triceps press", " triceps", 0),
            Exercise("seated two-arm palms-up low-pulley wrist curl", " forearms", 0),
            Exercise("see-saw press (alternating side press)", " shoulders", 0),
            Exercise("shotgun row", " lats", 0),
            Exercise("shoulder circles", " shoulders", 0),
            Exercise("shoulder press - with bands", " shoulders", 0),
            Exercise("shoulder raise", " shoulders", 0),
            Exercise("shoulder stretch", " shoulders", 0),
            Exercise("side bridge", " abdominals", 0),
            Exercise("side hop-sprint", " quadriceps", 0),
            Exercise("side jackknife", " abdominals", 0),
            Exercise("side lateral raise", " shoulders", 0),
            Exercise("side laterals to front raise", " shoulders", 0),
            Exercise("side leg raises", " adductors", 0),
            Exercise("side lying groin stretch", " adductors", 0),
            Exercise("side neck stretch", " neck", 0),
            Exercise("side standing long jump", " quadriceps", 0),
            Exercise("side to side box shuffle", " quadriceps", 0),
            Exercise("side to side chins", " lats", 0),
            Exercise("side wrist pull", " shoulders", 0),
            Exercise("side-lying floor stretch", " lats", 0),
            Exercise("single dumbbell raise", " shoulders", 0),
            Exercise("single leg butt kick", " quadriceps", 0),
            Exercise("single leg glute bridge", " glutes", 0),
            Exercise("single leg push-off", " quadriceps", 0),
            Exercise("single-arm cable crossover", " chest", 0),
            Exercise("single-arm linear jammer", " shoulders", 0),
            Exercise("single-arm push-up", " chest", 0),
            Exercise("single-cone sprint drill", " quadriceps", 0),
            Exercise("single-leg high box squat", " quadriceps", 0),
            Exercise("single-leg hop progression", " quadriceps", 0),
            Exercise("single-leg lateral hop", " quadriceps", 0),
            Exercise("single-leg leg extension", " quadriceps", 0),
            Exercise("single-leg stride jump", " quadriceps", 0),
            Exercise("sit squats", " quadriceps", 0),
            Exercise("sit-up", " abdominals", 0),
            Exercise("skating", " quadriceps", 0),
            Exercise("sled drag - harness", " quadriceps", 0),
            Exercise("sled overhead backward walk", " shoulders", 0),
            Exercise("sled overhead triceps extension", " triceps", 0),
            Exercise("sled push", " quadriceps", 0),
            Exercise("sled reverse flye", " shoulders", 0),
            Exercise("sled row", " middle back", 0),
            Exercise("sledgehammer swings", " abdominals", 0),
            Exercise("smith incline shoulder raise", " shoulders", 0),
            Exercise("smith machine behind the back shrug", " traps", 0),
            Exercise("smith machine bench press", " chest", 0),
            Exercise("smith machine bent over row", " middle back", 0),
            Exercise("smith machine calf raise", " calves", 0),
            Exercise("smith machine close-grip bench press", " triceps", 0),
            Exercise("smith machine decline press", " chest", 0),
            Exercise("smith machine hang power clean", " hamstrings", 0),
            Exercise("smith machine hip raise", " abdominals", 0),
            Exercise("smith machine incline bench press", " chest", 0),
            Exercise("smith machine leg press", " quadriceps", 0),
            Exercise("smith machine one-arm upright row", " shoulders", 0),
            Exercise("smith machine overhead shoulder press", " shoulders", 0),
            Exercise("smith machine pistol squat", " quadriceps", 0),
            Exercise("smith machine reverse calf raises", " calves", 0),
            Exercise("smith machine shrug", " traps", 0),
            Exercise("smith machine squat", " quadriceps", 0),
            Exercise("smith machine stiff-legged deadlift", " hamstrings", 0),
            Exercise("smith machine upright row", " traps", 0),
            Exercise("smith single-leg split squat", " quadriceps", 0),
            Exercise("snatch", " quadriceps", 0),
            Exercise("snatch balance", " quadriceps", 0),
            Exercise("snatch deadlift", " hamstrings", 0),
            Exercise("snatch from blocks", " quadriceps", 0),
            Exercise("snatch pull", " hamstrings", 0),
            Exercise("snatch shrug", " traps", 0),
            Exercise("speed band overhead triceps", " triceps", 0),
            Exercise("speed band pushdown", " triceps", 0),
            Exercise("speed box squat", " quadriceps", 0),
            Exercise("speed squats", " quadriceps", 0),
            Exercise("spell caster", " abdominals", 0),
            Exercise("spider crawl", " abdominals", 0),
            Exercise("spider curl", " biceps", 0),
            Exercise("spinal stretch", " middle back", 0),
            Exercise("split clean", " quadriceps", 0),
            Exercise("split jerk", " quadriceps", 0),
            Exercise("split jump", " quadriceps", 0),
            Exercise("split snatch", " hamstrings", 0),
            Exercise("split squat with dumbbells", " quadriceps", 0),
            Exercise("split squats", " hamstrings", 0),
            Exercise("squat jerk", " quadriceps", 0),
            Exercise("squat with bands", " quadriceps", 0),
            Exercise("squat with chains", " quadriceps", 0),
            Exercise("squat with plate movers", " quadriceps", 0),
            Exercise("squats - with bands", " quadriceps", 0),
            Exercise("stairmaster", " quadriceps", 0),
            Exercise("standing alternating dumbbell press", " shoulders", 0),
            Exercise("standing barbell calf raise", " calves", 0),
            Exercise("standing barbell press behind neck", " shoulders", 0),
            Exercise("standing bent-over one-arm dumbbell triceps extension", " triceps", 0),
            Exercise("standing bent-over two-arm dumbbell triceps extension", " triceps", 0),
            Exercise("standing biceps cable curl", " biceps", 0),
            Exercise("standing biceps stretch", " biceps", 0),
            Exercise("standing bradford press", " shoulders", 0),
            Exercise("standing cable chest press", " chest", 0),
            Exercise("standing cable lift", " abdominals", 0),
            Exercise("standing cable wood chop", " abdominals", 0),
            Exercise("standing calf raises", " calves", 0),
            Exercise("standing concentration curl", " biceps", 0),
            Exercise("standing dumbbell calf raise", " calves", 0),
            Exercise("standing dumbbell press", " shoulders", 0),
            Exercise("standing dumbbell reverse curl", " biceps", 0),
            Exercise("standing dumbbell straight-arm front delt raise above head", " shoulders", 0),
            Exercise("standing dumbbell triceps extension", " triceps", 0),
            Exercise("standing dumbbell upright row", " traps", 0),
            Exercise("standing elevated quad stretch", " quadriceps", 0),
            Exercise("standing front barbell raise over head", " shoulders", 0),
            Exercise("standing gastrocnemius calf stretch", " calves", 0),
            Exercise("standing hamstring and calf stretch", " hamstrings", 0),
            Exercise("standing hip circles", " abductors", 0),
            Exercise("standing hip flexors", " quadriceps", 0),
            Exercise("standing inner-biceps curl", " biceps", 0),
            Exercise("standing lateral stretch", " abdominals", 0),
            Exercise("standing leg curl", " hamstrings", 0),
            Exercise("standing long jump", " quadriceps", 0),
            Exercise("standing low-pulley deltoid raise", " shoulders", 0),
            Exercise("standing low-pulley one-arm triceps extension", " triceps", 0),
            Exercise("standing military press", " shoulders", 0),
            Exercise("standing olympic plate hand squeeze", " forearms", 0),
            Exercise("standing one-arm cable curl", " biceps", 0),
            Exercise("standing one-arm dumbbell curl over incline bench", " biceps", 0),
            Exercise("standing one-arm dumbbell triceps extension", " triceps", 0),
            Exercise("standing overhead barbell triceps extension", " triceps", 0),
            Exercise("standing palm-in one-arm dumbbell press", " shoulders", 0),
            Exercise("standing palms-in dumbbell press", " shoulders", 0),
            Exercise("standing palms-up barbell behind the back wrist curl", " forearms", 0),
            Exercise("standing pelvic tilt", " lower back", 0),
            Exercise("standing rope crunch", " abdominals", 0),
            Exercise("standing soleus and achilles stretch", " calves", 0),
            Exercise("standing toe touches", " hamstrings", 0),
            Exercise("standing towel triceps extension", " triceps", 0),
            Exercise("standing two-arm overhead throw", " shoulders", 0),
            Exercise("star jump", " quadriceps", 0),
            Exercise("step mill", " quadriceps", 0),
            Exercise("step-up with knee raise", " glutes", 0),
            Exercise("stiff leg barbell good morning", " lower back", 0),
            Exercise("stiff-legged barbell deadlift", " hamstrings", 0),
            Exercise("stiff-legged dumbbell deadlift", " hamstrings", 0),
            Exercise("stomach vacuum", " abdominals", 0),
            Exercise("straight bar bench mid rows", " middle back", 0),
            Exercise("straight raises on incline bench", " shoulders", 0),
            Exercise("straight-arm dumbbell pullover", " chest", 0),
            Exercise("straight-arm pulldown", " lats", 0),
            Exercise("stride jump crossover", " quadriceps", 0),
            Exercise("sumo deadlift", " hamstrings", 0),
            Exercise("sumo deadlift with bands", " hamstrings", 0),
            Exercise("sumo deadlift with chains", " hamstrings", 0),
            Exercise("superman", " lower back", 0),
            Exercise("supine chest throw", " triceps", 0),
            Exercise("supine one-arm overhead throw", " abdominals", 0),
            Exercise("supine two-arm overhead throw", " abdominals", 0),
            Exercise("suspended push-up", " chest", 0),
            Exercise("suspended reverse crunch", " abdominals", 0),
            Exercise("suspended row", " middle back", 0),
            Exercise("suspended split squat", " quadriceps", 0),
            Exercise("t-bar row with handle", " middle back", 0),
            Exercise("tate press", " triceps", 0),
            Exercise("the straddle", " hamstrings", 0),
            Exercise("thigh abductor", " abductors", 0),
            Exercise("thigh adductor", " adductors", 0),
            Exercise("tire flip", " quadriceps", 0),
            Exercise("toe touchers", " abdominals", 0),
            Exercise("torso rotation", " abdominals", 0),
            Exercise("trail running/walking", " quadriceps", 0),
            Exercise("trap bar deadlift", " quadriceps", 0),
            Exercise("tricep dumbbell kickback", " triceps", 0),
            Exercise("tricep side stretch", " triceps", 0),
            Exercise("triceps overhead extension with rope", " triceps", 0),
            Exercise("triceps pushdown", " triceps", 0),
            Exercise("triceps pushdown - rope attachment", " triceps", 0),
            Exercise("triceps pushdown - v-bar attachment", " triceps", 0),
            Exercise("triceps stretch", " triceps", 0),
            Exercise("tuck crunch", " abdominals", 0),
            Exercise("two-arm dumbbell preacher curl", " biceps", 0),
            Exercise("two-arm kettlebell clean", " shoulders", 0),
            Exercise("two-arm kettlebell jerk", " shoulders", 0),
            Exercise("two-arm kettlebell military press", " shoulders", 0),
            Exercise("two-arm kettlebell row", " middle back", 0),
            Exercise("underhand cable pulldowns", " lats", 0),
            Exercise("upper back stretch", " middle back", 0),
            Exercise("upper back-leg grab", " hamstrings", 0),
            Exercise("upright barbell row", " shoulders", 0),
            Exercise("upright cable row", " traps", 0),
            Exercise("upright row - with bands", " traps", 0),
            Exercise("upward stretch", " shoulders", 0),
            Exercise("v-bar pulldown", " lats", 0),
            Exercise("v-bar pullup", " lats", 0),
            Exercise("vertical swing", " hamstrings", 0),
            Exercise("walking", " treadmill", 0),
            Exercise("weighted ball hyperextension", " lower back", 0),
            Exercise("weighted ball side bend", " abdominals", 0),
            Exercise("weighted bench dip", " triceps", 0),
            Exercise("weighted crunches", " abdominals", 0),
            Exercise("weighted jump squat", " quadriceps", 0),
            Exercise("weighted pull ups", " lats", 0),
            Exercise("weighted sissy squat", " quadriceps", 0),
            Exercise("weighted sit-ups - with bands", " abdominals", 0),
            Exercise("weighted squat", " quadriceps", 0),
            Exercise("wide stance barbell squat", " quadriceps", 0),
            Exercise("wide stance stiff legs", " hamstrings", 0),
            Exercise("wide-grip barbell bench press", " chest", 0),
            Exercise("wide-grip decline barbell bench press", " chest", 0),
            Exercise("wide-grip decline barbell pullover", " chest", 0),
            Exercise("wide-grip lat pulldown", " lats", 0),
            Exercise("wide-grip pulldown behind the neck", " lats", 0),
            Exercise("wide-grip rear pull-up", " lats", 0),
            Exercise("wide-grip standing barbell curl", " biceps", 0),
            Exercise("wind sprints", " abdominals", 0),
            Exercise("windmills", " abductors", 0),
            Exercise("world's greatest stretch", " hamstrings", 0),
            Exercise("wrist circles", " forearms", 0),
            Exercise("wrist roller", " forearms", 0),
            Exercise("wrist rotations with straight bar", " forearms", 0),
            Exercise("yoke walk", " quadriceps", 0),
            Exercise("zercher squats", " quadriceps", 0),
            Exercise("zottman curl", " biceps", 0),
            Exercise("zottman preacher curl", " biceps", 0)))*/